import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { NoticeType } from '@fiduciary-interface/app/features/autogenerated-forms/models';
import { SpnService } from '../../services/bussiness/spn.service';
import { ProcurementNoticesService } from '../../services/api/procurement-notices.service';
import { ActivatedRoute, Router } from '@angular/router';
import { BiddingProcessProcurementProcess, Project } from '@core/models';
import { forkJoin, map, Observable, Subscription, switchMap } from 'rxjs';
import { LoadProjectDataService } from '@fiduciary-interface/app/features/autogenerated-forms/services/load-project-data.service';
import { UnitOfTime } from '../../models/spn.model';
import { BreadcrumbService } from 'xng-breadcrumb';
import { CategoryProcurement, PermissionEnum } from '@core/enums';
import { TranslateService } from '@ngx-translate/core';
import { SpnType } from '../../enums';

interface newInterface {
  processName: string;
  processCode: string;
  procurementProcess: BiddingProcessProcurementProcess;
  selectedLanguage: string;
  selectedProject: Project;
  country: string;
}

@Component({
  selector: 'fi-spn-preview-sdp',
  templateUrl: './spn-preview-sdp.component.html',
  styleUrls: ['./spn-preview-sdp.component.scss'],
})
export class SpnPreviewSdpComponent implements OnInit, OnDestroy {
  private procurementNoticeSvc = inject(ProcurementNoticesService);
  private projectDataSvc = inject(LoadProjectDataService);
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private spnSvc = inject(SpnService);
  private breadcrumbService = inject(BreadcrumbService);
  private translateService = inject(TranslateService);

  projectData$: Observable<newInterface> = this.projectDataSvc.loadDatatoSpn();
  data: any;

  optionsLangs = this.spnSvc.getLangOptions();
  loading;
  unitsOfTime: UnitOfTime[];
  sub: Subscription = new Subscription();
  noticeType = NoticeType;

  canEditNotice = [
    PermissionEnum.ENTER_UPDATE_CONTRACT_PROCUREMENT_INFORMATION,
  ];

  projectInfo = null;

  ngOnDestroy(): void {
    this.sub.unsubscribe();
  }

  ngOnInit(): void {
    this.loading = true;
    const noticesId = this.route.snapshot.paramMap.get('noticeId');
    const notice$ = this.procurementNoticeSvc.getSpn(noticesId);
    this.sub.add(
      this.projectData$
        .pipe(
          switchMap((projectData) =>
            notice$.pipe(
              switchMap((notice) =>
                forkJoin({
                  agaData: this.getAgaData(
                    projectData.selectedProject.projectBucketId,
                    projectData.selectedLanguage
                  ),
                  unitsOfTime: this.getUnitsOfTime(
                    projectData.selectedLanguage
                  ),
                }).pipe(
                  map(({ agaData, unitsOfTime }) => ({
                    projectData,
                    notice,
                    agaData,
                    unitsOfTime,
                  }))
                )
              )
            )
          )
        )
        .subscribe((data) => {
          const institution = this.translateService.instant('COMMON.IDB');
          this.projectInfo = {
            institutionName: institution,
            executor: data.projectData.selectedProject.executor,
            country: data.projectData.country,
            projectName: data.notice.projectName,
            operationNumber: data.projectData.selectedProject.operationNumber,
            contractNumber: data.projectData.selectedProject.contract,
            proposalTitle: data.projectData.processName,
            proposalNumber: data.projectData.processCode,
            economicSector: data.agaData.sector,
          };
          this.data = data;
          this.data.notice.lots = this.data.notice.lots.sort(
            (a, b) => a.number - b.number
          );
          this.spnSvc.isSDPNotice = this.data.notice.spnType === 'SDP';
          this.unitsOfTime = data.unitsOfTime;
          this.setBreadcrumb();
          this.loading = false;
        })
    );
  }

  getAgaData(projectBucketId: string, language: string) {
    return this.procurementNoticeSvc.getAgaInfo(projectBucketId).pipe(
      map((data) => {
        return {
          name: data.name[language],
          objective: data.objective[language],
          sector: data.sector[language],
        };
      })
    );
  }

  getUnitsOfTime(language: string) {
    return this.procurementNoticeSvc.unitsOfTime().pipe(
      map((data) => {
        return data.map((ut) => {
          return { id: ut.id, name: ut.names[language] };
        });
      })
    );
  }

  getValueOptions(options: any, id: string) {
    return options?.find((e) => e.id === id)?.name;
  }

  getKeyByValue(options: any, value: string) {
    return options?.find((e) => e.value === value)?.key;
  }

  editNotice() {
    const currentUrl = this.router.url;
    const newUrl = currentUrl.replace('/preview', '/update');
    this.router.navigateByUrl(newUrl);
  }

  goBack() {
    const currentUrl = this.router.url;
    this.navigateToDocPackages(currentUrl);
  }

  navigateToDocPackages(currentUrl: string): void {
    const segments = currentUrl.split('/');
    const docPackagesIndex = segments.indexOf('doc-packages');

    if (docPackagesIndex !== -1) {
      const newUrl = segments.slice(0, docPackagesIndex + 1).join('/');
      this.router.navigateByUrl(newUrl);
    }
  }

  getUnitOfTimeName(unitOfTimeId: string) {
    return this.unitsOfTime.find((unit) => unit.id === unitOfTimeId).name;
  }

  isSDP(): boolean {
    return this.data.notice.spnType === 'SDP';
  }

  setBreadcrumb() {
    const alias = this.isSDP() ? 'SPN.TITLE.SDP' : 'SPN.TITLE.SDO';
    this.breadcrumbService.set('@preview-spn', alias);
  }

  get isSDOGoods(): boolean {
    return (
      this.data.notice.spnType === SpnType.SDO &&
      this.data.projectData.procurementProcess.category.name ===
        CategoryProcurement.PROCT_GOODS
    );
  }

  get isSDONCSVC(): boolean {
    return (
      this.data.notice.spnType !== SpnType.SDP &&
      this.data.projectData.procurementProcess?.category.name ===
        CategoryProcurement.PROCT_NCSVC
    );
  }
}
