export enum FormTypesEnum {
  TEXTBOX = 'textbox',
  TEXTAREA = 'textarea',
  CHECKBOX = 'checkbox',
  DROPDONWLIST = 'dropdownlist',
  INPUTPHONE = 'inputphone',
  INPUTNUMERIC = 'inputnumeric',
  INPUTCURRENCY = 'inputcurrency',
  RADIOBUTTON = 'radiobutton',
  DATEPICKER = 'datepicker',
  DATETIMEPICKER = 'datetimepicker',
  CHECKBOXSPECIAL = 'checkboxSpecial',
  UPLOAD_DOCUMENT = 'uploadDocument',
  RADIOBUTTONSPECIAL = 'radiobuttonSpecial',
  DROPDOWNSPECIAL = 'dropdownlistSpecial',
  EVALUATED_BIDDERS = 'evaluatedBidders',
  RICHTEXT = 'richtext',
  TIMEPICKER = 'timepicker',
}
