import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { NonNullableFormBuilder, FormGroup, Validators } from '@angular/forms';
import {
  EoiFormData,
  EoiFormModel,
  EoiPostRequestModel,
} from '../../forms/eoi.forms';
import { DocumentDomain, PermissionEnum } from '@core/enums';
import {
  BehaviorSubject,
  combineLatest,
  map,
  of,
  shareReplay,
  switchMap,
  takeUntil,
  tap,
} from 'rxjs';
import {
  FiduciaryProcessDocument,
  GetFiduciaryProcessDocumentsIdResponse,
} from '@core/models';
import { VisibilityService } from '@core/services/view';
import { Observable, Subject } from 'rxjs';
import { RecipientFormData } from '@fiduciary-interface/app/features/autogenerated-forms/models/recipient-form.model';
import { ProjectInfo } from '@fiduciary-interface/app/features/autogenerated-forms/models';
import moment from 'moment';
import {
  DEADLINE_MINIMUM_DAYS,
  endHourValidator,
  eoiLimitDeadlineValidator,
  noEmptyStringValidator,
} from './register-eoi.validators';
import { LoadProjectDataService } from '@fiduciary-interface/app/features/autogenerated-forms/services/load-project-data.service';
import { ActivatedRoute, Router } from '@angular/router';
import {
  ConfirmCancelDialogData,
  ConfirmCancelDialogComponent,
} from '@fiduciary-interface/app/shared/components/confirm-cancel-dialog/confirm-cancel-dialog.component';
import { MatDialog } from '@angular/material/dialog';
import { EoiViewModel, GetEoiResponse } from '../../models/eoi.model';
import { TranslateService } from '@ngx-translate/core';
import { EoiApiService } from '@core/services/apis/fiduciary-process-api/eoi-api/eoi-api.service';
import { NotificationGlobalService } from '@fiduciary-interface/app/shared';
import { HttpErrorResponse } from '@angular/common/http';
import { ErrorResponseValidations } from '@core/models';
import { BreadcrumbService } from 'xng-breadcrumb';
import { BiddingProcessDocumentPackagesApiService } from '@core/services/apis/fiduciary-process-api/bidding-process-document-packages-api/bidding-process-document-packages-api.service';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { combineDateTime } from '@fiduciary-interface/app/features/spn/models/spn-spd.form';

@Component({
  selector: 'fi-register-eoi',
  templateUrl: './register-eoi.component.html',
  styleUrls: ['./register-eoi.component.scss'],
})
export class RegisterEoiComponent implements OnInit, OnDestroy {
  private fb = inject(NonNullableFormBuilder);
  private visibilityService = inject(VisibilityService);
  private loadProjectDataService = inject(LoadProjectDataService);
  private activatedRoute = inject(ActivatedRoute);
  private matDialogService = inject(MatDialog);
  private translateService = inject(TranslateService);
  private eoiApiService = inject(EoiApiService);
  private router = inject(Router);
  private globalNotificationService = inject(NotificationGlobalService);
  private breadcrumbService = inject(BreadcrumbService);
  private documentPackageService = inject(
    BiddingProcessDocumentPackagesApiService
  );

  projectInfoVm$: Observable<ProjectInfo>;
  currentEoi$: Observable<GetEoiResponse>;
  publicationNumber: string;
  selectedLanguage: string;

  vm$: Observable<{
    projectInfo: ProjectInfo;
    currentEoi?: GetEoiResponse;
    docGroups?: GetFiduciaryProcessDocumentsIdResponse;
    selectedLanguage: string;
  }>;

  /**
   ** Holds EOI ID of the current Expression of Interest being edited
   *  TODO Look for a better way to give context here on wether the form is in register or edit mode
   *  ? Maybe use a :mode url param to defined the mode
   */
  currentEoiId: string;

  originalEoiDoc: FiduciaryProcessDocument;

  isEditMode: boolean = Boolean(this.activatedRoute.snapshot.params['eoiId']);
  isAmendment: boolean = Boolean(
    this.activatedRoute.snapshot.params['groupId']
  );
  isEditAmendment: boolean = Boolean(
    this.router.url.includes('update-amendment')
  );

  isRegisterAmendment = Boolean(this.router.url.includes('register-amendment'));

  originalDeadLineDate: string;

  destroyed$ = new Subject<void>();
  isSubmitting$ = new BehaviorSubject<boolean>(false);

  registerButtonPermissions: PermissionEnum[] = [
    PermissionEnum.ENTER_UPDATE_CONTRACT_PROCUREMENT_INFORMATION,
  ];

  pasteCleanupSettings = {
    convertMsLists: true,
    removeHtmlComments: true,
    // stripTags: ['span', 'h1'],
    // removeAttributes: ['lang'],
    removeMsClasses: true,
    removeMsStyles: true,
    removeInvalidHTML: true,
  };

  eoiFormGroup: FormGroup<EoiFormModel>;

  deadlineMinDate = new Date();

  projectName: string = '';

  constructor(private sanitizer: DomSanitizer) {
    this.eoiFormGroup = this.fb.group<EoiFormModel>({
      processSummary: this.fb.control<string>('', [Validators.required]),
      receptionDeadLine: this.fb.control<moment.Moment>(null, [
        Validators.required,
        eoiLimitDeadlineValidator(),
      ]),
      receptionDeadLineHour: this.fb.control<string>('', [Validators.required]),
      projectName: this.fb.control<string>('', [Validators.required]),
      consultingServices: this.fb.control<string>('', [
        Validators.required,
        noEmptyStringValidator(4000),
      ]),
      exceptionalEligibilityRules: this.fb.control<string>(''),
      startOperationHour: this.fb.control<string>('', [Validators.required]),
      endOperationHour: this.fb.control<string>('', [Validators.required]),
      electronicOffers: this.fb.control<boolean>(false),
      qualificationDemonstration: this.fb.control<string>('', [
        Validators.required,
        noEmptyStringValidator(4000),
      ]),
      linksRelatedWithTheDocument: this.fb.control<string[]>([]),
      recipient: this.fb.control<RecipientFormData>(null),
    });

    this.eoiFormGroup.controls.endOperationHour.addValidators(
      endHourValidator(this.eoiFormGroup.controls.startOperationHour)
    );
  }

  ngOnInit(): void {
    this.setBreadcrumb();

    this.eoiFormGroup.controls.startOperationHour.valueChanges
      .pipe(takeUntil(this.destroyed$))
      .subscribe(() => {
        const control = this.eoiFormGroup.controls.endOperationHour;
        control.updateValueAndValidity();
      });

    this.visibilityService.setVisiblityProjectHeader(false);

    this.getViewModel();
  }

  showInvalidFormDialog() {
    const dialogData: ConfirmCancelDialogData = {
      headerEnum: 'UNDB.FORM.INCOMPLETE_FORM.DIALOG.HEADER',
      bodyTextEnum: 'UNDB.FORM.INCOMPLETE_FORM.DIALOG.BODY',
      confirmButtonEnum: 'UNDB.FORM.INCOMPLETE_FORM.DIALOG.CONFIRM_BTN',
    };

    this.matDialogService.open(ConfirmCancelDialogComponent, {
      data: dialogData,
    });
  }

  onRegisterSuccess(response: string) {
    this.isSubmitting$.next(false);
    const message = this.translateService.instant(
      'UNDB.EOI.FORM.SUCCESFUL_REGISTRATION'
    );
    this.globalNotificationService.showSuccess(message);
    this.router.navigate(['../preview/', response], {
      relativeTo: this.activatedRoute,
    });
  }

  /**
   * Used by both registerEoi and updateEoi methods when their respective requests fails
   * @param error
   */
  onRequestError(error: HttpErrorResponse) {
    this.isSubmitting$.next(false);
    const e = error.error as ErrorResponseValidations;
    this.globalNotificationService.showError(e.detail);
  }

  registerEoi() {
    this.isSubmitting$.next(true);

    const postRequestData = this.mapFormRequestData(
      this.eoiFormGroup.getRawValue()
    );

    this.eoiApiService.registerEoi(postRequestData).subscribe({
      next: (res) => {
        this.onRegisterSuccess(res);
      },
      error: (err: HttpErrorResponse) => {
        this.onRequestError(err);
      },
    });
  }

  onUpdateSuccess(eoiId: string) {
    this.isSubmitting$.next(false);
    const message = this.translateService.instant(
      'UNDB.EOI.FORM.SUCCESFUL_UPDATE'
    );
    this.globalNotificationService.showSuccess(message);
    this.router.navigate(['../../', 'preview', eoiId], {
      relativeTo: this.activatedRoute,
    });
  }

  updateEoi() {
    this.isSubmitting$.next(true);

    const postRequestData = this.mapFormRequestData(
      this.eoiFormGroup.getRawValue()
    );

    this.eoiApiService.updateEoi(postRequestData, this.currentEoiId).subscribe({
      next: () => {
        this.onUpdateSuccess(this.currentEoiId);
      },
      error: (err: HttpErrorResponse) => {
        this.onRequestError(err);
      },
    });
  }

  onRegisterAmendSuccess(noticeId: string) {
    this.isSubmitting$.next(false);
    const msg = this.translateService.instant('UNDB.EOI.AMENDMENT_SUCCESS');
    this.globalNotificationService.showSuccess(msg);
    const groupId = this.activatedRoute.snapshot.params['groupId']; // This used when doing amendments to an eoi
    this.router.navigate(['../../', 'preview', noticeId, groupId], {
      relativeTo: this.activatedRoute,
    });
  }

  registerEoiAmendment() {
    this.isSubmitting$.next(true);
    const postRequestData = this.mapFormRequestData(
      this.eoiFormGroup.getRawValue()
    );

    this.eoiApiService.registerEoi(postRequestData).subscribe({
      next: (res) => {
        this.onRegisterAmendSuccess(res);
      },
      error: (err) => {
        this.isSubmitting$.next(false);
        this.onRequestError(err);
      },
    });
  }

  onUpdateAmendmentSuccess(eoiId: string) {
    this.isSubmitting$.next(false);
    const msg = this.translateService.instant('UNDB.EOI.AMENDMENT_SUCCESS');
    this.globalNotificationService.showSuccess(msg);
    const groupId = this.activatedRoute.snapshot.params['groupId']; // This used when doing amendments to an eoi
    this.router.navigate(['../../', 'preview', eoiId, groupId], {
      relativeTo: this.activatedRoute,
    });
  }

  updateEoiAmendment() {
    this.isSubmitting$.next(true);
    const postRequestData = this.mapFormRequestData(
      this.eoiFormGroup.getRawValue()
    );

    this.eoiApiService.updateEoi(postRequestData, this.currentEoiId).subscribe({
      next: () => {
        this.onUpdateAmendmentSuccess(this.currentEoiId);
      },
      error: (err) => {
        this.isSubmitting$.next(false);
        this.onRequestError(err);
      },
    });
  }

  onFormSubmit() {
    if (this.eoiFormGroup.invalid) {
      this.eoiFormGroup.markAllAsTouched();
      this.showInvalidFormDialog();
      return;
    }

    if (this.isEditMode) {
      this.updateEoi();
      return;
    }

    if (this.isRegisterAmendment) {
      this.registerEoiAmendment();
      return;
    }
    if (this.isEditAmendment) {
      this.updateEoiAmendment();
      return;
    }

    this.registerEoi();
  }

  prefillLimitDate() {
    /**
     * If we are editing an EOI form (wether is edit registered eoi, amend a published eoi or editing an amendment)
     * we dont prefill the date this field will be populated with the fetched data from the current EOI
     */
    if (this.isEditMode || this.isAmendment) return;
    let limitDateControl = this.eoiFormGroup.controls.receptionDeadLine;
    const now: moment.Moment = moment(moment.now());
    const fourteenDaysFromNow = now.add(DEADLINE_MINIMUM_DAYS, 'days');

    limitDateControl.setValue(fourteenDaysFromNow, {
      emitEvent: true,
    });
    limitDateControl.updateValueAndValidity();
  }

  getViewModel() {
    this.projectInfoVm$ = this.createProjectInfoVm();

    this.currentEoiId = this.activatedRoute.snapshot.params['eoiId'];
    const groupId = this.activatedRoute.snapshot.params['groupId']; // This used when doing amendments to an eoi

    const docGroup$ = this.getOrderedDocumentsObs(groupId);

    // When in doing an amendment we pass the docId as URL param and not the noticeId, we access the notice id from the doc group to get notice data and patch the form
    this.currentEoi$ = this.isAmendment
      ? this.getEoiByDocGroup(docGroup$)
      : this.getEoiById(this.currentEoiId);

    if (this.isEditMode) {
      this.vm$ = combineLatest({
        projectInfo: this.projectInfoVm$,
        currentEoi: this.currentEoi$,
        selectedLanguage: this.loadProjectDataService.selectedLanguage$,
      }).pipe(
        map(({ projectInfo, currentEoi, selectedLanguage }) => {
          return {
            projectInfo: {
              ...projectInfo,
              projectName: currentEoi.projectName,
            },
            currentEoi,
            selectedLanguage,
          };
        })
      );
    } else if (this.isAmendment) {
      this.vm$ = combineLatest({
        projectInfo: this.projectInfoVm$,
        docGroup: docGroup$,
        currentEoi: this.currentEoi$,
        selectedLanguage: this.loadProjectDataService.selectedLanguage$,
      }).pipe(
        map(({ projectInfo, docGroup, currentEoi, selectedLanguage }) => {
          return {
            projectInfo: {
              ...projectInfo,
              projectName: currentEoi.projectName,
            },
            docGroup,
            currentEoi,
            selectedLanguage,
          };
        })
      );
    } else {
      this.vm$ = combineLatest({
        projectInfo: this.projectInfoVm$,
        currentEoi: of(null as GetEoiResponse),
        selectedLanguage: this.loadProjectDataService.selectedLanguage$,
      });
    }

    // Trigger prefill of today date once the vm resolves
    this.vm$ = this.vm$.pipe(
      tap((vm) => {
        if (!vm.currentEoi) {
          this.prefillLimitDate();
        }
      })
    );
  }

  getEoiById(eoiId: string): Observable<GetEoiResponse> {
    return this.eoiApiService
      .getEoiById(eoiId)
      .pipe(
        map((eoi) => {
          return {
            ...eoi,
            startOperationHour: this.removeSeconds(eoi.startOperationHour),
            endOperationHour: this.removeSeconds(eoi.endOperationHour),
          };
        })
      )
      .pipe(tap((currentEoi) => this.patchForm(currentEoi)));
  }

  addDeadlineLimitValidator(baseDate?: string, days?: number) {
    const control = this.eoiFormGroup.controls.receptionDeadLine;
    control.clearValidators();
    control.addValidators(eoiLimitDeadlineValidator(baseDate, days));
  }

  getOrderedDocumentsObs(
    groupId: string
  ): Observable<FiduciaryProcessDocument[]> {
    return this.documentPackageService
      .getFiduciaryProcessDocuments(
        groupId,
        DocumentDomain.BIDDINGPROCESSDOCUMENTGROUP
      )
      .pipe(
        map((res) =>
          (
            res as GetFiduciaryProcessDocumentsIdResponse
          ).fiduciaryProcessDocuments.sort(
            (a, b) => a.noticeVersion - b.noticeVersion
          )
        )
      );
  }

  /**
   * Elimina los 3 últimos caracteres de una cadena de texto
   * @param {string} str - La hora en formato HH:mm:ss
   * @returns {string} La hora sin los segundos
   */
  removeSeconds(str) {
    return str.slice(0, -3);
  }

  getEoiByDocGroup(
    docGroup$: Observable<FiduciaryProcessDocument[]>
  ): Observable<GetEoiResponse> {
    return docGroup$.pipe(
      switchMap((docs) => {
        const latestDoc = docs[docs.length - 1];
        this.currentEoiId = latestDoc.noticeId;
        this.originalEoiDoc = docs.find((d) => d.noticeVersion === 0);
        return this.eoiApiService.getEoiById(latestDoc.noticeId).pipe(
          map((eoi) => {
            return {
              ...eoi,
              startOperationHour: this.removeSeconds(eoi.startOperationHour),
              endOperationHour: this.removeSeconds(eoi.endOperationHour),
            };
          }),
          tap((currentEoi) =>
            this.patchForm(currentEoi, this.originalEoiDoc.publicationDate)
          )
        );
      })
    );
  }

  prefillProcessSummary(processSummary: string) {
    if (this.isEditMode || this.isAmendment) return;
    this.eoiFormGroup.controls.processSummary.patchValue(processSummary);
  }

  prefillProjectName(projectName: string) {
    if (this.isEditMode || this.isAmendment) return;
    const control = this.eoiFormGroup.controls.projectName;
    control.patchValue(projectName);
  }

  createProjectInfoVm(): Observable<ProjectInfo> {
    // Observable containing project, procurement, language and complementary data
    const projectData$: Observable<EoiViewModel> = this.loadProjectDataService
      .loadEoiData()
      .pipe(shareReplay(1), takeUntil(this.destroyed$));

    // Maps the data from projectData$ to a format that the project info header can receive
    return projectData$.pipe(
      tap((p) => {
        this.projectName =
          p.projectComplementaryData.name[p.selectedLanguage].trim();
        this.prefillProcessSummary(p.procurementProcess.name);
        this.prefillProjectName(this.projectName || p.selectedProject.nameEn);
        this.selectedLanguage = p.selectedLanguage;
      }),
      map((vm: EoiViewModel) => {
        const projectInfo: ProjectInfo = {
          institutionName: this.translateService.instant('COMMON.IDB'),
          executor: vm.selectedProject.executor,
          country: vm.projectCountry,
          projectName: vm.selectedProject.projectName[vm.selectedLanguage],
          operationNumber: vm.selectedProject.operationNumber,
          contractNumber: vm.selectedProject.contract,
          proposalTitle: vm.procurementProcess.name,
          proposalNumber: vm.procurementProcess.code,
          economicSector:
            vm.projectComplementaryData.sector[vm.selectedLanguage],
        };

        return projectInfo;
      }),
      takeUntil(this.destroyed$)
    );
  }

  mapFormRequestData(formData: EoiFormData): EoiPostRequestModel {
    const documentPackageId =
      this.activatedRoute.snapshot.params['documentPackageId'];

    const dataClone = { ...formData };
    const recipient = this.eoiFormGroup.controls.recipient.value;
    delete dataClone.recipient;
    const receptionDeadLine = combineDateTime(
      this.eoiFormGroup.controls.receptionDeadLine.value,
      this.eoiFormGroup.controls.receptionDeadLineHour.value
    ).toISOString();
    delete dataClone.receptionDeadLineHour;
    const qualificationDemonstration = this.safeHtmlToString(
      this.sanitizeHtml(
        this.eoiFormGroup.controls.qualificationDemonstration.value
      )
    );
    const consultingServices = this.safeHtmlToString(
      this.sanitizeHtml(this.eoiFormGroup.controls.consultingServices.value)
    );

    const postRequestData: EoiPostRequestModel = {
      documentPackageId,
      ...dataClone,
      ...recipient,
      receptionDeadLine,
      qualificationDemonstration,
      consultingServices,
      isAmendment: this.isAmendment,
    };

    return postRequestData;
  }

  onExit() {
    const dialogData: ConfirmCancelDialogData = {
      headerIcon: 'info',
      headerEnum: 'UNDB.FORM.EXIT_DIALOG.HEADER',
      bodyTextEnum: 'UNDB.FORM.EXIT_DIALOG.BODY',
      cancelButtonEnum: 'ANT_TRANSACTION.CANCEL',
      confirmButtonEnum: 'UNDB.FORM.EXIT_DIALOG.CONFIRM_BTN',
    };

    if (this.isEditMode) {
      dialogData.bodyTextEnum = 'UNDB.FORM.EXIT_DIALOG.EDIT_EOI.BODY';
      dialogData.headerEnum = 'UNDB.FORM.EXIT_DIALOG.EDIT_EOI.HEADER';
    }

    const dialog = this.matDialogService.open(ConfirmCancelDialogComponent, {
      data: dialogData,
    });

    dialog
      .afterClosed()
      .pipe(
        tap((res) => {
          if (res) {
            this.onExitConfirmation();
          }
        })
      )
      .subscribe();
  }

  sanitizeHtml(
    html: string,
    allowedStyles: string[] = ['text-align'],
    allowedValues: { [key: string]: string[] } = {
      'text-align': ['left', 'center', 'right'],
      'font-weight': ['normal', 'bold', '600'],
    }
  ): SafeHtml {
    // Crear un elemento temporal para trabajar con el DOM
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = html;

    // Procesar todos los elementos con atributos style, pero preservar estructura
    this.processStyles(tempDiv, allowedStyles, allowedValues);

    // Devolver el HTML con la estructura original, solo limpiando estilos
    return this.sanitizer.bypassSecurityTrustHtml(tempDiv.innerHTML);
  }

  /**
   * Procesa recursivamente los nodos del DOM eliminando solo estilos no permitidos
   */
  private processStyles(
    node: Node,
    allowedStyles: string[],
    allowedValues: { [key: string]: string[] }
  ): void {
    // Si es un elemento HTML
    if (node.nodeType === Node.ELEMENT_NODE) {
      const element = node as HTMLElement;

      // Sanitizar ÚNICAMENTE el atributo style
      if (element.hasAttribute('style')) {
        const sanitizedStyle = this.sanitizeStyle(
          element.getAttribute('style') || '',
          allowedStyles,
          allowedValues
        );

        // Si hay estilos permitidos, establecer el atributo, sino eliminarlo
        if (sanitizedStyle) {
          element.setAttribute('style', sanitizedStyle);
        } else {
          element.removeAttribute('style');
        }
      }

      // Procesar los hijos recursivamente
      Array.from(element.childNodes).forEach((child) => {
        this.processStyles(child, allowedStyles, allowedValues);
      });
    }
  }

  /**
   * Filtra y sanitiza las propiedades de estilo
   */
  private sanitizeStyle(
    styleAttr: string,
    allowedStyles: string[],
    allowedValues: { [key: string]: string[] }
  ): string {
    // Dividir el string de estilo en propiedades individuales
    const styleProps = styleAttr
      .split(';')
      .map((prop) => prop.trim())
      .filter((prop) => prop !== '');

    // Filtrar solo las propiedades y valores permitidos
    const sanitizedProps = styleProps.filter((prop) => {
      const [name, value] = prop.split(':').map((part) => part.trim());

      // Si no tiene formato válido (nombre:valor)
      if (!name || !value) {
        return false;
      }

      // Verificar si la propiedad está en la lista de permitidos
      if (!allowedStyles.includes(name)) {
        return false;
      }

      // Si hay una lista de valores permitidos para esta propiedad
      if (allowedValues[name]) {
        // Verificar si el valor está permitido
        return allowedValues[name].includes(value);
      }

      // Si no hay una lista específica de valores para esta propiedad, permitirla
      return true;
    });

    // Unir las propiedades permitidas en un string
    return sanitizedProps.join('; ');
  }

  safeHtmlToString(safeHtml: SafeHtml): string {
    return (
      safeHtml as unknown as { changingThisBreaksApplicationSecurity: string }
    ).changingThisBreaksApplicationSecurity;
  }

  onExitConfirmation() {
    if (this.isEditMode || this.isAmendment) {
      this.router.navigate(['../../../../'], {
        relativeTo: this.activatedRoute,
      });
      return;
    }

    this.router.navigate(['../../../'], {
      relativeTo: this.activatedRoute,
    });
  }

  /**
   *
   * @param currentEoi
   * @param publicationDate
   */
  patchForm(currentEoi: GetEoiResponse, publicationDate?: string) {
    this.publicationNumber = currentEoi.publicationNumber;
    const {
      address,
      email,
      executingAgency,
      phone,
      responsible,
      webSite,
      receptionDeadLine,
      ...rest
    } = currentEoi;
    this.originalDeadLineDate = receptionDeadLine.split('T')[0];

    const formPatchData: EoiFormData = {
      ...rest,
      qualificationDemonstration: rest.qualificationDemonstration,
      receptionDeadLine: moment(receptionDeadLine),
      receptionDeadLineHour: receptionDeadLine.includes("T00:00") ?
        '' :
        receptionDeadLine.split('T')[1].slice(0,5),
      projectName:
        this.projectName === '' ? currentEoi.projectName : this.projectName,
      recipient: {
        address,
        email,
        executingAgency,
        phone,
        responsible,
        website: webSite,
      },
    };

    // we set the min date of the date picker to today to 14 days in the future
    this.setDeadlineDatePickerMinDate(moment(moment.now()).add(14, 'days'));

    if (publicationDate) {
      // If the notice was already published the minimum for the deadline is 14 days since the day of publication
      formPatchData.receptionDeadLine = moment(publicationDate).add(14, 'days');
      this.addDeadlineLimitValidator(publicationDate);
      this.setDeadlineDatePickerMinDate(formPatchData.receptionDeadLine);
    }

    this.eoiFormGroup.patchValue(formPatchData);
    this.eoiFormGroup.controls.receptionDeadLine.markAsTouched();
  }

  setDeadlineDatePickerMinDate(minDate: moment.Moment) {
    this.deadlineMinDate = new Date(minDate.toISOString());

    this.eoiFormGroup.controls.receptionDeadLine.markAsTouched();
  }

  actualReceptionDeadLine() {
    return this.eoiFormGroup.controls.receptionDeadLine.value
      .toISOString()
      .split('T')[0];
  }

  ngOnDestroy(): void {
    this.destroyed$.next();
    this.destroyed$.complete();
  }

  setBreadcrumb() {
    if (this.isEditMode) {
      this.breadcrumbService.set(
        '@eoi-update',
        'ENUM.PROCESS.DOCUMENT.GROUP.STANDARD_DOCUMENT_TERMS_REF'
      );
    }

    if (this.isRegisterAmendment) {
      this.breadcrumbService.set(
        '@eoi-register-amendment',
        'ENUM.PROCESS.DOCUMENT.GROUP.STANDARD_DOCUMENT_TERMS_REF'
      );
    }

    if (this.isEditAmendment) {
      this.breadcrumbService.set(
        '@eoi-update-amendment',
        'ENUM.PROCESS.DOCUMENT.GROUP.STANDARD_DOCUMENT_TERMS_REF'
      );
    }

    this.breadcrumbService.set(
      '@eoi-register',
      'ENUM.PROCESS.DOCUMENT.GROUP.STANDARD_DOCUMENT_TERMS_REF'
    );
  }

  getControlLength(control: string) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(
      this.eoiFormGroup.value[control],
      'text/html'
    );
    const length = doc.body.textContent.replace(/\s/g, '').trim().length;
    return length || 0;
  }
}
