# You need to configure the root folder of the Angular or JavaScript project to be scanned
sonar.sources=./src
# If you need to configure any file and/or folder that need to be excluded from the scanning. 
#   E.g.: Image files, Third-party JavaScript. 
#  Regular expression is allowed.
sonar.exclusions=**/dist/*, **/bin/*, **/obj/*, **/node_modules/*, **/src/test/*

# If you need to change the encoding of the files to be scanned. 
sonar.sourceEncoding=UTF-8

# ╔═╗┬  ┌─┐┌─┐┌─┐┌─┐  ┌┬┐┌─┐┌┐┌┌┬┐  ┌─┐┬ ┬┌─┐┌┐┌┌─┐┌─┐
# ╠═╝│  ├┤ ├─┤└─┐├┤    │││ ││││ │   │  ├─┤├─┤││││ ┬├┤ 
# ╩  ┴─┘└─┘┴ ┴└─┘└─┘  ─┴┘└─┘┘└┘ ┴   └─┘┴ ┴┴ ┴┘└┘└─┘└─┘
sonar.host.url=@SONAR_URL@
sonar.login=@SECRET@