export enum DocumentGroupCode {
  CLARIFICATIONS = 10,
  BIDDINDG_DOC_BID_VALIDITY = 31,
  EXPRESSION_INTEREST_NOTICE = 49,
  OTHER = 33,
  OTHER_AFTER_COMPLETION = 58,
  BANK_RESPONSE_AFTER_COMPLETION = 63,
  BANK_RESPONSE = 5,
  UBO_DOCUMENT = 64,
}
