import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import {
  filter,
  map,
  Observable,
  shareReplay,
  takeUntil,
  Subject,
  combineLatest,
} from 'rxjs';
import { ProjectStoreService } from '@core/services/store-services';
import { LoadProjectDataService } from '@fiduciary-interface/app/features/autogenerated-forms/services/load-project-data.service';
import { EoiViewModel, GetEoiResponse } from '../../models/eoi.model';
import { ActivatedRoute, Router } from '@angular/router';
import { EoiApiService } from '@core/services/apis/fiduciary-process-api/eoi-api/eoi-api.service';
import { TranslateService } from '@ngx-translate/core';
import { ProjectInfo } from '@fiduciary-interface/app/features/autogenerated-forms/models';
import { BreadcrumbService } from 'xng-breadcrumb';
import { PermissionEnum } from '@core/enums';
import moment from 'moment';

@Component({
  selector: 'fi-preview-eoi',
  templateUrl: './preview-eoi.component.html',
  styleUrls: ['./preview-eoi.component.scss'],
})
export class PreviewEoiComponent implements OnDestroy, OnInit {
  private projectStoreService = inject(ProjectStoreService);
  private loadProjectDataService = inject(LoadProjectDataService);
  private activatedRoute = inject(ActivatedRoute);
  private eoiApiService = inject(EoiApiService);
  private translateService = inject(TranslateService);
  private breadcrumbService = inject(BreadcrumbService);
  private router = inject(Router);

  canPublishNotice: PermissionEnum[] = [
    PermissionEnum.SEND_OFFICIAL_PROCUREMENT_COMUNICATIONS,
  ];

  destroyed$ = new Subject<void>();
  publicationNumber: string;

  currentEoi$ = this.eoiApiService.getEoiById(
    this.activatedRoute.snapshot.params['eoiId']
  );

  hasGroupId = this.activatedRoute.snapshot.params['groupId'];
  hasEoIId = this.activatedRoute.snapshot.params['eoiId'];
  isReadonly = Boolean(this.router.url.includes('readonly'));

  hasEzShare$ = this.eoiApiService.hasEzShare(
    this.activatedRoute.snapshot.params['documentPackageId']
  );

  projectData$ = this.loadProjectDataService.loadEoiData();

  paragraphsVm$: Observable<{
    projectData: EoiViewModel;
    currentEoi: GetEoiResponse;
    hasEzShare: { hasEzShare: boolean; docId: any };
  }> = combineLatest({
    projectData: this.projectData$,
    currentEoi: this.currentEoi$,
    hasEzShare: this.hasEzShare$,
  }).pipe(shareReplay(1), takeUntil(this.destroyed$));

  projectInfoVm$ = this.paragraphsVm$.pipe(
    map(({ projectData, hasEzShare, currentEoi }) => {
      this.publicationNumber = currentEoi.publicationNumber;
      const projectInfo: ProjectInfo = {
        institutionName: this.translateService.instant('COMMON.IDB'),
        executor: projectData.selectedProject.executor,
        country: projectData.projectCountry,
        projectName:
          projectData.selectedProject.projectName[
            projectData.selectedLanguage
          ].trim() ||
          currentEoi.projectName ||
          projectData.selectedProject.nameEn,
        operationNumber: projectData.selectedProject.operationNumber,
        contractNumber: projectData.selectedProject.contract,
        proposalNumber: projectData.procurementProcess.code,
        proposalTitle: projectData.procurementProcess.name,
        economicSector:
          projectData.projectComplementaryData.sector[
            projectData.selectedLanguage
          ],
      };

      return { projectInfo, hasEzShare };
    }),
    takeUntil(this.destroyed$)
  );

  vm$ = combineLatest({
    paragraphs: this.paragraphsVm$,
    projectInfo: this.projectInfoVm$,
  });

  ngOnInit(): void {
    this.setBreadcrumb();
  }

  selectedProject$ = this.projectStoreService.selectedProject().pipe(
    filter((selectedProject) => !!selectedProject && selectedProject.loaded),
    map((selectedProject) => selectedProject.selectedProject)
  );

  goToEditNotice() {
    if (this.hasGroupId) {
      this.router.navigate(
        [
          '../../..',
          this.activatedRoute.snapshot.params['groupId'],
          'update-amendment',
        ],
        { relativeTo: this.activatedRoute }
      );
      return;
    }
    this.router.navigate(
      ['../..', this.activatedRoute.snapshot.params['eoiId'], 'update'],
      { relativeTo: this.activatedRoute }
    );
  }

  ngOnDestroy() {
    this.destroyed$.next();
    this.destroyed$.complete();
  }

  exitPreview() {
    let route = ['../../../../'];
    if (this.hasGroupId) {
      route = ['../../../../../'];
      if (this.isReadonly) route = ['../../../../../../'];
    }
    this.router.navigate(route, { relativeTo: this.activatedRoute });
  }

  formatWorkingHours(startHour: string, endingHour: string): string {
    return `${moment(startHour, 'HH:mm').format(
      'HH:mm'
    )} ${this.translateService.instant(
      'UNDB.PREVIEW.OPERATION_HOURS.TO'
    )} ${moment(endingHour, 'HH:mm').format('HH:mm')}`;
  }

  formatWorkingHour(startHour: string): string {
    return `${moment(startHour, 'HH:mm').format('hh:mm A')}`;
  }

  setBreadcrumb() {
    if (this.hasGroupId) {
      this.breadcrumbService.set(
        '@eoi-preview-amendment',
        'ENUM.PROCESS.DOCUMENT.GROUP.STANDARD_DOCUMENT_TERMS_REF'
      );
      return;
    }

    this.breadcrumbService.set(
      '@eoi-preview',
      'ENUM.PROCESS.DOCUMENT.GROUP.STANDARD_DOCUMENT_TERMS_REF'
    );
  }
}
