import {
  AbstractControl,
  FormArray,
  FormControl,
  FormGroup,
  ValidationErrors,
  Validators,
} from '@angular/forms';
import { FormType } from '@core/utils';
import {
  AccompanimentOptions,
  ElectronicOptions,
  LotsOptions,
  MatchingDirectionOptions,
} from '../enums';
import { RecipientFormData } from '../../autogenerated-forms/models/recipient-form.model';
import { MarginOfPreferenceWillBeGranted } from '../enums/marginOfPreferenceWillBeGranted.enum';
import { noEmptyStringValidator } from '../../eoi/views/register-eoi/register-eoi.validators';

export interface SpnSpdForm {
  spnType: string;
  agaCode: string;
  projectName: string;
  agaPublicationDate: Date;
  agenciesWillBeCofinanced: string;
  withLots: string;
  worksToBeAcquired: string;
  timeQuantity: number;
  timeUnit: string;
  exceptionalEligibilityRules: string;
  qualificationRequirements: string;
  languageOfBiddingDocuments: string;
  nonRefundableAmountCurrency: string;
  nonRefundableAmountPaymentMethod: string;
  nonRefundableAmount: number;
  howToSendBiddingDocument: string;
  linksRelatedWithTheDocument: string;
  dateOfSubmissionOfBids: Date;
  dateTimeOfSubmissionOfBids: string;
  electronicOffers: string;
  bidOpeningDate: Date;
  dateTimebidOpeningDate: string;
  typeOfAccompaniment: string;
  isSameOpeningAddress: string;
  bidOpeningAddress: string;
  bidSubmissionAddress: string;
  responsibleAddress: string;
  responsibleName: string;
  responsibleEmail: string;
  responsiblePhone: string;
  recipient: Recipient;
  lots: SpnSpdLots[];
  bidSecurityOption: number;
  currency: string;
  amountInCurrency: number;
  percentageOfBidPrice: number;
  marginOfPreferenceWillBeGranted?: string | boolean;
  mofMethod?: boolean;
  negotiationMethod?: boolean;
  /* addressBidSubmission: string; */
  /* bidMaintenanceGuarantee: SpnSpdBidMaintenance; */
}

export interface Recipient {
  address: string;
  executingAgency: string;
  responsible: string;
  phone: string;
  email: string;
  website: string;
}

export interface SpnSpdLots {
  number: number;
  name: string;
  expectedTime: number;
  timeUnit: number;
  technicalSpecifications: string;
}

export interface SpnSpdBidMaintenance {
  currency: string;
  amountInCurrency: number;
  percentageOfBidPrice: number;
}

export function SpnSpdFormAll(isSdp = true): FormType<SpnSpdForm> {
  const formControls = {
    spnType: new FormControl(null, Validators.required),
    agaCode: new FormControl(null, Validators.required),
    agaPublicationDate: new FormControl(null, Validators.required),
    agenciesWillBeCofinanced: new FormControl(null, Validators.maxLength(500)),
    withLots: new FormControl(String(LotsOptions.NO_LOTS), [
      Validators.required,
    ]),
    projectName: new FormControl<string>('', [Validators.required]),
    worksToBeAcquired: new FormControl(null, Validators.maxLength(500)),
    timeQuantity: new FormControl(null, Validators.min(0)),
    timeUnit: new FormControl(),
    exceptionalEligibilityRules: new FormControl(
      null,
      Validators.maxLength(500)
    ),
    qualificationRequirements: new FormControl('', [
      Validators.required,
      noEmptyStringValidator(4000),
    ]),
    languageOfBiddingDocuments: new FormControl(null, [Validators.required]),
    nonRefundableAmountCurrency: new FormControl(),
    nonRefundableAmountPaymentMethod: new FormControl(
      null,
      Validators.maxLength(100)
    ),
    nonRefundableAmount: new FormControl(),
    howToSendBiddingDocument: new FormControl(null, [Validators.required]),
    linksRelatedWithTheDocument: new FormControl(),
    dateOfSubmissionOfBids: new FormControl(null, [Validators.required]),
    dateTimeOfSubmissionOfBids: new FormControl(null, [Validators.required]),
    electronicOffers: new FormControl(String(ElectronicOptions.YES), [
      Validators.required,
    ]),
    bidOpeningDate: new FormControl(null, [Validators.required]),
    dateTimebidOpeningDate: new FormControl(null, [Validators.required]),
    typeOfAccompaniment: new FormControl(
      String(AccompanimentOptions.GUARANTEE),
      Validators.required
    ),
    isSameOpeningAddress: new FormControl(
      String(MatchingDirectionOptions.SAME)
    ),
    bidOpeningAddress: new FormControl(null, Validators.maxLength(500)),
    bidSubmissionAddress: new FormControl(null, Validators.maxLength(500)),
    responsibleAddress: new FormControl(null, [
      Validators.required,
      Validators.maxLength(100),
    ]),
    responsibleName: new FormControl(null, [
      Validators.required,
      Validators.maxLength(100),
    ]),
    responsibleEmail: new FormControl(null, [
      Validators.required,
      Validators.email,
      Validators.maxLength(100),
    ]),
    responsiblePhone: new FormControl(null, [Validators.maxLength(100)]),
    recipient: recipientForm(),
    bidSecurityOption: new FormControl(),
    currency: new FormControl(),
    amountInCurrency: new FormControl(),
    percentageOfBidPrice: new FormControl(),
    lots: new FormArray([]),
  };
  if (!isSdp) {
    formControls['marginOfPreferenceWillBeGranted'] = new FormControl(
      MarginOfPreferenceWillBeGranted.GRANTED,
      Validators.required
    );
    formControls['mofMethod'] = new FormControl(false);
    formControls['negotiationMethod'] = new FormControl(false);
  }
  return new FormGroup(formControls, dateComparisonValidator);
}

export function recipientForm(): FormType<RecipientFormData> {
  return new FormGroup({
    address: new FormControl(null, [Validators.required]),
    email: new FormControl(null, [Validators.required, Validators.email]),
    executingAgency: new FormControl(null, [Validators.required]),
    phone: new FormControl(null, []),
    responsible: new FormControl(null, [Validators.required]),
    website: new FormControl(null, []),
  });
}

export function SpnSpdLotsForm(): FormType<SpnSpdLots> {
  return new FormGroup({
    expectedTime: new FormControl<number>(null, [
      Validators.required,
      Validators.min(1),
    ]),
    name: new FormControl('', Validators.required),
    number: new FormControl<number>(null, Validators.required),
    technicalSpecifications: new FormControl('', Validators.required),
    timeUnit: new FormControl(null, Validators.required),
  });
}

export function SpnSpdBidMaintenanceForm(): FormType<SpnSpdBidMaintenance> {
  return new FormGroup({
    amountInCurrency: new FormControl(),
    currency: new FormControl(),
    percentageOfBidPrice: new FormControl(),
  });
}

export function minOneItemValidator(
  control: AbstractControl
): ValidationErrors | null {
  return control.value && control.value.length > 0
    ? null
    : { minOneItem: true };
}

const TIME_FORMAT_REGEX = /^\d{2}:\d{2}$/;

export function combineDateTime(dateISO, timeString) {
  if (!TIME_FORMAT_REGEX.test(timeString)) {
    return new Date(dateISO);
  }

  const [hours, minutes] = timeString.split(':').map(Number);
  const date = new Date(dateISO);
  date.setUTCHours(hours, minutes, 0, 0);

  return date;
}

function dateComparisonValidator(formGroup) {
  const {
    dateOfSubmissionOfBids: startDate,
    dateTimeOfSubmissionOfBids: startTime,
    bidOpeningDate: endDate,
    dateTimebidOpeningDate: endTime,
  } = formGroup.controls;

  if (
    !startDate?.value ||
    !endDate?.value ||
    !startTime?.value ||
    !endTime?.value
  ) {
    return null;
  }

  const start = combineDateTime(startDate.value, startTime.value);
  const end = combineDateTime(endDate.value, endTime.value);

  // Diferencia en milisegundos, convertida a minutos
  const differenceInMinutes = (end.getTime() - start.getTime()) / 60000;

  return differenceInMinutes >= 0 ? null : { dateInvalid: true };
}

export enum BidSecurityOptions {
  AMOUNT = 0,
  PERCENTAGE,
}
