import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ProjectInfoComponent } from './components/project-info/project-info.component';
import { TranslateModule } from '@ngx-translate/core';
import { ParagraphSectionComponent } from './components/paragraph-section/paragraph-section.component';
import { OptionalFieldComponent } from './components/optional-field/optional-field.component';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatInputModule } from '@angular/material/input';
import { FormDividerComponent } from './components/form-divider/form-divider.component';
import { UndbRecipientComponent } from './components/undb-recipient/undb-recipient.component';
import { UndbRecipientComponentGroup } from './components/undb-recipient-group/undb-recipient.component';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { MatDatepickerModule } from '@angular/material/datepicker';
import {
  DateAdapter,
  MAT_DATE_FORMATS,
  MAT_DATE_LOCALE,
  MatDateFormats,
} from '@angular/material/core';
import { MatButtonModule } from '@angular/material/button';
import { PipeModule } from '@fiduciary-interface/app/shared';
import { UndbLinkedDocumentsComponent } from './components/undb-linked-documents/undb-linked-documents.component';
import { UndbDatePickerComponent } from './components/undb-date-picker/undb-date-picker.component';
import {
  MAT_MOMENT_DATE_ADAPTER_OPTIONS,
  MatMomentDateModule,
  MomentDateAdapter,
} from '@angular/material-moment-adapter';
import { TimePickerComponent } from './components/time-picker/time-picker.component';
import { TimeMaskDirective } from './directives/time-mask.directive';
import { RichTextEditorComponent } from './components/rich-text-editor/rich-text-editor.component';

export const CUSTOM_DATE_FORMATS: MatDateFormats = {
  parse: {
    dateInput: 'DD MMM YYYY', // Parsing format
  },
  display: {
    dateInput: 'DD MMMM YYYY', // Display format in the input field
    monthYearLabel: 'MMMM YYYY', // Format for month-year in calendar header
    dateA11yLabel: 'LL', // Accessibility label
    monthYearA11yLabel: 'MMMM YYYY', // Accessibility label for month-year
  },
};
@NgModule({
  declarations: [
    OptionalFieldComponent,
    ProjectInfoComponent,
    ParagraphSectionComponent,
    FormDividerComponent,
    UndbRecipientComponent,
    UndbLinkedDocumentsComponent,
    UndbRecipientComponentGroup,
    UndbDatePickerComponent,
    TimePickerComponent,
    TimeMaskDirective,
    RichTextEditorComponent,
  ],
  imports: [
    CommonModule,
    MatIconModule,
    MatFormFieldModule,
    MatTooltipModule,
    TranslateModule,
    MatInputModule,
    FormsModule,
    ReactiveFormsModule,
    MatDatepickerModule,
    MatMomentDateModule,
    MatButtonModule,
    PipeModule,
    FormsModule,
  ],
  exports: [
    OptionalFieldComponent,
    ProjectInfoComponent,
    ParagraphSectionComponent,
    FormDividerComponent,
    UndbRecipientComponent,
    UndbRecipientComponentGroup,
    UndbLinkedDocumentsComponent,
    UndbDatePickerComponent,
    TimePickerComponent,
    TimeMaskDirective,
    RichTextEditorComponent,
  ],
  providers: [
    { provide: DateAdapter, useClass: MomentDateAdapter },
    { provide: MAT_DATE_FORMATS, useValue: CUSTOM_DATE_FORMATS },
    { provide: MAT_DATE_LOCALE, useValue: 'en-US' },
    { provide: MAT_MOMENT_DATE_ADAPTER_OPTIONS, useValue: { useUtc: false } },
  ],
})
export class AutogeneratedFormsModule {}
