import { RouterTestingModule } from '@angular/router/testing';
import { CUSTOM_ELEMENTS_SCHEMA, NO_ERRORS_SCHEMA } from '@angular/core';
import { provideMockStore } from '@ngrx/store/testing';
import { DocBtnsComponent } from './doc-btns.component';
import { render, screen } from '@testing-library/angular';
import { BiddingProcessDocumentPackage } from '@core/models';
import { TranslateTestingModule } from 'ngx-translate-testing';
import { HttpClientTestingModule } from '@angular/common/http/testing';
import { NotificationService } from '@progress/kendo-angular-notification';
import { ActivatedRoute } from '@angular/router';
import { DirectivesModule } from '@fiduciary-interface/app/shared/directives/directives.module';
import { MsalTestModule } from '@fiduciary-interface/test/msal-test/msal-test.module';
import { ReactiveFormsModule } from '@angular/forms';
import { DatePipe } from '@angular/common';
import { DialogModule } from '@progress/kendo-angular-dialog';
import { BPbtns } from '../../enums';
import { MatDialogProviders } from '@fiduciary-interface/test/test-helpers';

const docPackage: BiddingProcessDocumentPackage = {
  actualDate: new Date('2022-02-10T15:38:57.4665326'),
  biddingProcessDocumentGroups: [
    {
      documentGroupCode: 0,
      documentGroupConfiguration: {
        disclosureRequiredAmount: false,
        id: '313181ba-80e4-402e-848a-211d84980950',
        isAmendment: false,
        isAutogenerated: true,
        isClarification: false,
        isDisclosed: false,
        isMandatory: true,
        isResult: false,
        isUniqueDocument: true,
        result: 0,
        visibility: 1,
        systemUpload: false,
        isMandatoryPublication: null,
      },
      documentsState: { loading: false },
      fiduciaryProcessDocuments: [
        {
          description: '',
          created: new Date('2021-12-15T19:39:07.9939219'),
          createdBy: '',
          ezshareNumber: '',
          groupCode: 0,
          id: 'b8540300-de57-4d68-9e24-567193af0ea0',
          modified: new Date('2021-12-15T19:39:54.4722004'),
          name: 'CO-L1229-P18-BIDDINDG_DOC_PREQUALIFICATION-FIDUCIARY_CONFIGURATIONS_V5.xlsx',
          operationsDocumentId: null,
          relationalId: '8703425b-3f16-4d2f-95f8-4dbcf9348e56',
          status: 1,
          type: 2,
        },
        {
          description: '',
          created: new Date('2021-12-20T18:03:47.0317602'),
          createdBy: '',
          ezshareNumber: '',
          groupCode: 0,
          id: '9de71919-e8c8-44c1-9199-e281107fc367',
          modified: new Date('2021-12-23T20:13:35.9512905'),
          name: 'CO-L1229-P18-BIDDINDG_DOC_PREQUALIFICATION-Actuaciones_1696566 (5).xls',
          operationsDocumentId: null,
          relationalId: '32eaa2d7-b5a5-4dda-8ef0-f7159dab2f4a',
          status: 1,
          type: 2,
        },
      ],
      id: '2793940e-42c2-432f-8da5-3225547013c5',
    },
    {
      documentGroupCode: 1,
      documentGroupConfiguration: {
        disclosureRequiredAmount: false,
        id: '2802596b-d277-47c8-8b7f-089d499275b9',
        isAmendment: true,
        isAutogenerated: true,
        isClarification: false,
        isDisclosed: false,
        isMandatory: true,
        isResult: false,
        isUniqueDocument: true,
        result: 0,
        visibility: 1,
        systemUpload: false,
        isMandatoryPublication: null,
      },
      documentsState: { loading: false },
      fiduciaryProcessDocuments: [
        {
          description: '',
          created: new Date('2022-02-10T15:38:57.4665326'),
          createdBy: '',
          ezshareNumber: 'EZTEST-1654199927-842',
          groupCode: 1,
          id: '77ea0625-fa6c-43e1-89bf-8b3811407c85',
          modified: new Date('2022-02-17T17:25:24.3559133'),
          name: 'CO-L1229-P18-BIDDINDG_DOC_INVITATION-FIDUCIARY_CONFIGURATIONS_V5.xlsx',
          operationsDocumentId: null,
          relationalId: '1281cbcb-e38e-4e88-af9e-5ab24980b3b3',
          status: 3,
          type: 2,
        },
        {
          description: '',
          created: new Date('2021-12-15T19:39:26.0071326'),
          createdBy: '',
          ezshareNumber: 'EZTEST-130319487-47',
          groupCode: 1,
          id: '7159e37a-3967-4875-b234-2de09a6bba5c',
          modified: new Date('2021-12-22T16:15:36.6644278'),
          name: 'CO-L1229-P18-BIDDINDG_DOC_OTHER-FIDUCIARY_CONFIGURATIONS_V5 (1).xlsx',
          operationsDocumentId: null,
          relationalId: '3b5a59ac-8103-4c77-8928-bc69b345951f',
          status: 3,
          type: 2,
        },
      ],
      id: 'ea536ef4-044b-45df-bb8f-3b082ffb5c32',
    },
  ],
  code: 0,
  documentsState: { loading: false },
  groupsState: { loading: false },
  id: '7c9cffaa-7877-438b-9512-0e608a57e2a4',
  order: 3,
  requireNonObjection: false,
  status: 1,
  totalComments: 0,
  totalMandatoryDocuments: 2,
  totalUploadedDocuments: 1,
  documentsToUpload: [],
  bidValidityExtensionDate: new Date(),
};
const documentPackages: BiddingProcessDocumentPackage[] = [];

async function setup(initialStatus: number = 0) {
  const mockActivatedRoute = {
    snapshot: {
      params: {
        processId: 'id',
      },
    },
  };

  const initialState = getInitialState();
  const { fixture } = await render(DocBtnsComponent, {
    declarations: [DocBtnsComponent],
    componentProperties: {
      procurementProcess: {
        advanceMilestone: {
          total: 0,
          totalCompleted: 0,
          delayed: true,
          currentMilestone: null,
        },
        bafo: true,
        biddingProcessPlanId: '12312312',
        category: {
          name: '',
          id: 2,
        },
        code: '',
        componentName: '',
        description: '',
        goodsReference: 0,
        id: '',
        justification: '',
        lots: 22,
        manualId: '',
        name: '',
        totalAcumulatedAmount: 0,
        procurementMethod: {
          name: '',
          id: 0,
        },
        projectAmount: {
          cofinancedAmount: 0,
          estimatedAmount: 0,
          idbAmount: 0,
          localCounterpartAmount: 0,
          costJustification: '',
        },
        sepaPeclaId: '',
        status: 2,
        subExecutor: '',
        supervisionMethod: {
          id: 2,
          name: '',
        },
        sustainability: null,
        sustainabilityDescription: '',
        totalComments: 0,
        isMigrated: true,
        packagesUnderReview: true,
        isUpdated: true,
        procurementProcessComments: [],
        order: 43,
      },
      docPackage: { ...docPackage, status: initialStatus },
      documentPackages: { ...documentPackages },
    },
    schemas: [NO_ERRORS_SCHEMA, CUSTOM_ELEMENTS_SCHEMA],
    imports: [
      ReactiveFormsModule,
      MsalTestModule,
      DirectivesModule,
      DialogModule,
      HttpClientTestingModule,
      RouterTestingModule,
      TranslateTestingModule.withTranslations(
        'en',
        require('../../../../../../assets/i18n/en.json')
      ).withDefaultLanguage('en'),
    ],
    providers: [
      provideMockStore({ initialState }),
      NotificationService,
      DatePipe,
      { provide: ActivatedRoute, useValue: mockActivatedRoute },
      ...MatDialogProviders,
    ],
  });
  const component = fixture.componentInstance;
  return { component, fixture };
}

function getInitialState() {
  return {
    biddingProcessPlan: {
      selectedBiddingProcessProcurementProcess: {
        code: 'CO-L1229-P39',
        id: '1e064f09-7d62-4b59-8c05-ff1dced92a66',
        projectAmount: {
          estimatedAmount: 60_000_000,
        },
      },
    },
  };
}

describe('DocBtnsComponent', () => {
  it('should create', async () => {
    const { component } = await setup();
    expect(component).toBeTruthy();
  });
  it('should showBtnSpnCategoryGoods to be true', async () => {
    const { component } = await setup();
    component.procurementProcess = {
      isMigrated: false,
      packagesUnderReview: false,
      biddingProcessPlanId: 'b4952feb-3947-4d10-bd3c-923d4adbbbd7',
      code: 'PN-L1095-P00127',
      description: 'CFI-6759-8',
      sustainabilityDescription: '',
      totalAcumulatedAmount: 0,
      totalComments: 0,
      advanceMilestone: {
        totalCompleted: 1,
        total: 10,
        delayed: true,
        currentMilestone: null,
      },
      componentName: 'Componente 1. Electrificación rural en red',
      bafo: null,
      sepaPeclaId: '',
      lots: null,
      category: {
        name: 'PROCT_GOODS',
        id: 5,
      },
      procurementMethod: {
        name: 'PROCT_CBSSTEWP',
        id: 79,
      },
      supervisionMethod: {
        name: 'ExPost',
        id: 1,
      },
      status: 7,
      sustainability: null,
      goodsReference: null,
      id: '49a2f749-2ed1-4fa3-8ebc-0abbf707a9fc',
      manualId: '',
      name: 'CFI-6759-8',
      projectAmount: {
        estimatedAmount: 666,
        localCounterpartAmount: 222,
        idbAmount: 222,
        cofinancedAmount: 222,
        costJustification: null,
      },
      subExecutor: '',
      justification: '',
      isUpdated: true,
      procurementProcessComments: [],
      order: 4,
    };
    component.ngOnInit();
    expect(component.showBtnSpnCategoryGoods).toBe(true);
  });

  describe('Submits packages buttons visibility', () => {
    it('should submitPackageForDisclosure', async () => {
      const { component, fixture } = await setup();
      component.display = true;
      component.footerVisibility = true;
      component.BPBtnDictionary[BPbtns.Disclosure].showBtn = true;
      component.BPBtnDictionary[BPbtns.Disclosure].tooltip = 'true';
      component.BPBtnDictionary[BPbtns.Disclosure].disableBtn = false;
      fixture.detectChanges();

      const eventSpy = jest.spyOn(component, 'submitForDisclosure');
      screen.getByText('Submit for Disclosure').click();
      expect(eventSpy).toHaveBeenCalled();
    });

    it('should submitForNonObjection', async () => {
      const { component, fixture } = await setup();
      component.footerVisibility = true;
      component.BPBtnDictionary[BPbtns.NonObjection].showBtn = true;
      component.BPBtnDictionary[BPbtns.NonObjection].tooltip = 'true';
      component.BPBtnDictionary[BPbtns.NonObjection].disableBtn = false;
      fixture.detectChanges();

      const eventSpy = jest.spyOn(component, 'submitForNonObjection');
      screen.getByText('Request non-objection').click();
      expect(eventSpy).toHaveBeenCalled();
    });

    it('should confirmPackage', async () => {
      const { component, fixture } = await setup();
      component.footerVisibility = true;
      component.BPBtnDictionary[BPbtns.Confirm].showBtn = true;
      component.BPBtnDictionary[BPbtns.Confirm].tooltip = 'true';
      component.BPBtnDictionary[BPbtns.Confirm].disableBtn = false;

      fixture.detectChanges();
      const eventSpy = jest.spyOn(component, 'confirmPackage');
      screen.getByText('Confirm Package').click();
      expect(eventSpy).toHaveBeenCalled();
    });
    it('should ConfirmAmendment', async () => {
      const { component, fixture } = await setup();
      component.footerVisibility = true;
      component.BPBtnDictionary[BPbtns.ConfirmAmendment].showBtn = true;
      component.BPBtnDictionary[BPbtns.ConfirmAmendment].tooltip = 'true';
      component.BPBtnDictionary[BPbtns.ConfirmAmendment].disableBtn = false;

      fixture.detectChanges();
      const eventSpy = jest.spyOn(component, 'confirmPackage');
      screen.getByText('Confirm Amendment Upload').click();
      expect(eventSpy).toHaveBeenCalled();
    });
    it('should ConfirmClarificationUpload', async () => {
      const { component, fixture } = await setup();
      component.footerVisibility = true;
      component.BPBtnDictionary[BPbtns.ConfirmClarificationUpload].showBtn =
        true;
      component.BPBtnDictionary[BPbtns.ConfirmClarificationUpload].tooltip =
        'true';
      component.BPBtnDictionary[BPbtns.ConfirmClarificationUpload].disableBtn =
        false;

      fixture.detectChanges();
      const eventSpy = jest.spyOn(component, 'confirmPackage');
      screen.getByText('Confirm Clarification Upload').click();
      expect(eventSpy).toHaveBeenCalled();
    });

    it('should RequestAmendment', async () => {
      const { component, fixture } = await setup();
      component.footerVisibility = true;
      component.BPBtnDictionary[BPbtns.RequestAmendment].showBtn = true;
      component.BPBtnDictionary[BPbtns.RequestAmendment].tooltip = 'true';
      component.BPBtnDictionary[BPbtns.RequestAmendment].disableBtn = false;
      fixture.detectChanges();

      const eventSpy = jest.spyOn(component, 'submitForNonObjection');
      screen.getByText('Request Amendment Non-Objection').click();
      expect(eventSpy).toHaveBeenCalled();
    });
  });

  describe('Buttons error toast if date not filled', () => {
    it('should show toast error in submitPackageForDisclosure', async () => {
      docPackage.actualDate = null;
      const { component, fixture } = await setup();
      component.display = true;
      component.footerVisibility = true;
      component.BPBtnDictionary[BPbtns.Disclosure].showBtn = true;
      component.BPBtnDictionary[BPbtns.Disclosure].tooltip = 'true';
      component.BPBtnDictionary[BPbtns.Disclosure].disableBtn = false;
      fixture.detectChanges();

      const eventSpy = jest.spyOn(component, 'showErrorToast');
      screen.getByText('Submit for Disclosure').click();
      expect(eventSpy).toHaveBeenCalled();
    });

    it('should show toast error in submitForNonObjection', async () => {
      docPackage.actualDate = null;
      const { component, fixture } = await setup();
      component.footerVisibility = true;
      component.BPBtnDictionary[BPbtns.NonObjection].showBtn = true;
      component.BPBtnDictionary[BPbtns.NonObjection].tooltip = 'true';
      component.BPBtnDictionary[BPbtns.NonObjection].disableBtn = false;
      fixture.detectChanges();

      const eventSpy = jest.spyOn(component, 'showErrorToast');
      screen.getByText('Request non-objection').click();
      expect(eventSpy).toHaveBeenCalled();
    });
    it('should show toast error in confirmPackage ', async () => {
      docPackage.actualDate = null;
      const { component, fixture } = await setup();
      component.display = true;
      component.footerVisibility = true;
      component.BPBtnDictionary[BPbtns.Confirm].showBtn = true;
      component.BPBtnDictionary[BPbtns.Confirm].tooltip = 'true';
      component.BPBtnDictionary[BPbtns.Confirm].disableBtn = false;
      fixture.detectChanges();

      const eventSpy = jest.spyOn(component, 'showErrorToast');
      screen.getByText('Confirm Package').click();
      expect(eventSpy).toHaveBeenCalled();
    });
  });

  describe('Documents result', () => {
    it('should return undefined if no result document package exists', async () => {
      const { component } = await setup();
      const result = component.getResultDocumentPackage();

      expect(result).toBeUndefined();
    });

    it('should return the result document package number if it exists', async () => {
      const { component } = await setup();
      docPackage.biddingProcessDocumentGroups[0].documentGroupConfiguration.isResult = true;
      docPackage.biddingProcessDocumentGroups[0].documentGroupConfiguration.result = 123;
      const result = component.getResultDocumentPackage();
      expect(result).toBe(123);
    });
  });

  it('successResponse', async () => {
    const { component, fixture } = await setup();
    const response = {
      status: 1,
    };
    const eventSpy = jest
      .spyOn(component, 'showSuccessToast')
      .mockReturnValue();
    const eventSpy2 = jest.spyOn(
      component.documentPackageStore,
      'changeDocumentPackageStatusSuccessAction'
    );
    fixture.detectChanges();
    component.successResponse(response);
    expect(eventSpy).toHaveBeenCalled();
    expect(eventSpy2).toHaveBeenCalled();
  });
  it('showSuccessToast', async () => {
    const { component } = await setup();
    const eventSpy = jest
      .spyOn(component.notificationGlobalService, 'showSuccess')
      .mockReturnValue();
    component.showSuccessToast();
    expect(eventSpy).toHaveBeenCalled();
  });
  it('reload', async () => {
    const { component } = await setup();
    const reloadMock = jest.fn();
    const locationMock = {
      ...window.location,
      reload: reloadMock,
    };
    Object.defineProperty(window, 'location', { value: locationMock });

    component.reload();
    expect(reloadMock).toHaveBeenCalled();
  });
  it('showErrorToast', async () => {
    const { component } = await setup();
    const eventSpy = jest
      .spyOn(component.notificationGlobalService, 'showError')
      .mockReturnValue();
    const eventSpy2 = jest.spyOn(
      component.documentPackageStore,
      'changeDocumentPackageStatusErrorAction'
    );
    component.showErrorToast();

    expect(eventSpy).toHaveBeenCalled();
    expect(eventSpy2).toHaveBeenCalled();
  });
});
