export const Activities = {
    ACTVITIES_IN_PROGRESS: 'ACTIVITIES.IN_PROGRESS',
    ACTIVTIES_START_WORKFLOW: 'Start Workflow',
    ACTVITIES_INPROGRESS: 'InProgress',
    ACTVITIES_ENTER_SUBMIT: 'EnterAndSubmit',
    ACTIVITIES_WORKFLOW_FINANCIAL_TRANSACTION: 'ACTIVITIES.FINANCIAL_TRANSACTION'
};
