import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SpnRoutingModule } from './spn-routing.module';
import { TranslateModule } from '@ngx-translate/core';
import { AutogeneratedFormsModule } from '../autogenerated-forms/autogenerated-forms.module';
import { SpnComponent } from './components/spn/spn.component';
import { OptionalParagraphComponent } from '../autogenerated-forms/components/optional-paragraph/optional-paragraph.component';
import { OptionsFormsComponent } from '../autogenerated-forms/components/options-forms/options-forms.component';
import { InfoFormComponent } from '../autogenerated-forms/components/info-form/info-form.component';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { MatInputModule } from '@angular/material/input';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatNativeDateModule } from '@angular/material/core';
import { MatRadioModule } from '@angular/material/radio';
import { RegisterSpnSpdComponent } from './views/register-spn-spd/register-spn-spd.component';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { SpnLotsComponent } from './components/spn-lots/spn-lots.component';
import { DateTimePickerComponent } from '../autogenerated-forms/components/date-time-picker/date-time-picker.component';
import { MatNumericComponent } from '@fiduciary-interface/app/shared/components/mat-numeric/mat-numeric.component';
import { SpnPreviewComponent } from './components/spn-preview/spn-preview.component';
import { SpnPreviewSdpComponent } from './components/spn-preview-sdp/spn-preview-sdp.component';
import { SpnPreviewSdoComponent } from './components/spn-preview-sdo/spn-preview-sdo.component';
import { MatDateComponent } from '@fiduciary-interface/app/shared/components/mat-date/mat-date.component';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { PipeModule } from '@fiduciary-interface/app/shared';
import { MatTableModule } from '@angular/material/table';
import { MatAutocompleteModule } from '@angular/material/autocomplete';
import { EditorModule } from '@progress/kendo-angular-editor';
import { SpnPreviewSdpEsComponent } from './components/spn-preview-sdp/components/spn-preview-sdp-es/spn-preview-sdp-es.component';
import { SpnPreviewSdpEnComponent } from './components/spn-preview-sdp/components/spn-preview-sdp-en/spn-preview-sdp-en.component';
import { SpnPreviewSdpPtComponent } from './components/spn-preview-sdp/components/spn-preview-sdp-pt/spn-preview-sdp-pt.component';
import { SpnPreviewSdpFrComponent } from './components/spn-preview-sdp/components/spn-preview-sdp-fr/spn-preview-sdp-fr.component';
import { SpnPreviewSdpBaseComponent } from './components/spn-preview-sdp/components/spn-preview-sdp-base/spn-preview-sdp-base.component';

@NgModule({
  declarations: [
    RegisterSpnSpdComponent,
    SpnComponent,
    SpnLotsComponent,
    SpnPreviewComponent,
    SpnPreviewSdpComponent,
    SpnPreviewSdoComponent,
    SpnPreviewSdpEsComponent,
    SpnPreviewSdpEnComponent,
    SpnPreviewSdpPtComponent,
    SpnPreviewSdpFrComponent,
    SpnPreviewSdpBaseComponent,
  ],
  imports: [
    CommonModule,
    SpnRoutingModule,
    TranslateModule,
    AutogeneratedFormsModule,
    OptionalParagraphComponent,
    OptionsFormsComponent,
    InfoFormComponent,
    MatFormFieldModule,
    MatSelectModule,
    ReactiveFormsModule,
    MatInputModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatRadioModule,
    MatCheckboxModule,
    FormsModule,
    MatTooltipModule,
    MatIconModule,
    MatButtonModule,
    MatProgressSpinnerModule,
    DateTimePickerComponent,
    MatNumericComponent,
    MatDateComponent,
    PipeModule,
    MatTableModule,
    EditorModule,
    MatAutocompleteModule,
  ],
})
export class SpnModule {}
