import { FormControl } from '@angular/forms';
import { RecipientFormData } from '../../autogenerated-forms/models/recipient-form.model';

export type EoiFormModel = {
  [key in keyof EoiFormData]: FormControl<EoiFormData[key]>;
};

export interface EoiFormData {
  processSummary: string;
  receptionDeadLine: moment.Moment;
  receptionDeadLineHour?: string;
  consultingServices: string;
  exceptionalEligibilityRules: string;
  startOperationHour: string;
  endOperationHour: string;
  electronicOffers: boolean;
  qualificationDemonstration: string;
  projectName: string;
  linksRelatedWithTheDocument: Array<string>;
  recipient: RecipientFormData;
}

type Flatten<T> = {
  [K in keyof T as K extends 'recipient'
    ? keyof T[K] extends string
      ? `${keyof T[K]}`
      : never
    : K]: K extends 'recipient'
    ? T[K][keyof T[K]]
    : T[K] extends moment.Moment
    ? string // Convert moment.Moment to string
    : T[K];
};

export type EoiPostRequestModel = Flatten<EoiFormData> & {
  documentPackageId: string;
  isAmendment: boolean;
};
