export enum BiddingContractAmendmentDocumentGroupCode {
  CONTACT_AWARD = 0,
  BANK_RESPONSE = 1,
  CONTRACT_COMPLETION = 2,
  OTHER = 3,
  CONTRACT_TERMINATION = 5,
  DRAFT_CONTRACT_AMENDMENT = 7,
  SIGNED_CONTRACT_AMENDMENT = 8,
  AMENDMENT_BANK_RESPONSE = 12,
}
