export enum BiddingContractStatusesEnum {
  AMENDMENT_UNDER_REV = 0,
  EXECUTION,
  EXECUTION_AMENDMENTS,
  FINISHED,
  PENDING_SIGNATURE,
  SIGNED,
  TERMINATED,
  TERMINATION_UNDER_REV,
  DELETED,
  AMENDMENT_REVIEWED,
  EXPIRED,
  RETURNED_WITH_COMMENTS,
}
