export enum BiddingContractDocumentGroupCode {
  BANK_RESPONSE = 1,
  CONTRACT_COMPLETION,
  OTHER,
  SIGNED_CONTRACT,
  CONTRACT_TERMINATION,
  DRAFT_CONTRACT,
  AWARD_CONTRACT = 9,
  AMENDMENT_DOC_OTHER,
  BANK_RESPONSE_AFTER_COMPLETION,
  AMEDMENT_BANK_RESPONSE,
}
