export enum CategoryProcurement {
  PROCT_WORKS = 'PROCT_WORKS',
  PROCT_GOODS = 'PROCT_GOODS',
  PROCT_NCSVC = 'PROCT_NCSVC',
  PROCT_CSTFRM = 'PROCT_CSTFRM',
  PROCT_INDCST = 'PROCT_INDCST',
  PROCT_EXT_AUDIT = 'PROCT_EXT_AUDIT',
}

// export enum CategoryProcurement {
//   CONSULTING_FIRMS = 'CONSULTING_FIRMS',
//   EXTERNAL_AUDIT = 'EXTERNAL_AUDIT',
//   GOODS = 'GOODS',
//   INDIVIDUAL_CONSULTANTS = 'INDIVIDUAL_CONSULTANTS',
//   NON_CONSULTING_SERVICES = 'NON_CONSULTING_SERVICES',
//   WORKS = 'WORKS',
// }
