export enum ChangeProcess {
  PROCESS_NAME = 'FI.CNVG.FP.PROCUREMENT.PROCESS_NAME',
  MANUAL_ID = 'FI.CNVG.FP.PROCUREMENT.MANUAL_ID',
  DESCRIPTION = 'FI.CNVG.FP.PROCUREMENT.DESCRIPTION',
  SUB_EXECUTOR = 'FI.CNVG.FP.PROCUREMENT.SUB_EXECUTOR',
  CATEGORY = 'FI.CNVG.FP.PROCUREMENT.CATEGORY',
  ACQUISITION_METHOD = 'FI.CNVG.FP.PROCUREMENT.ACQUISITION_METHOD',
  MONITORING_METHOD = 'FI.CNVG.FP.PROCUREMENT.MONITORING_METHOD',

  TOTAL_AMOUNT_OF_CONTRACT = 'FI.CNVG.FP.CONTRACT.COST_DISTRIBUTION.TOTAL_AMOUNT_OF_CONTRACT',
  IADB_AMOUNT = 'FI.CNVG.FP.CONTRACT.COST_DISTRIBUTION.IADB_AMOUNT',
  LOCAL_COUNTERPART_AMOUNT = 'FI.CNVG.FP.CONTRACT.COST_DISTRIBUTION.LOCAL_COUNTERPART_AMOUNT',
  COFINANCING_AMOUNT = 'FI.CNVG.FP.CONTRACT.COST_DISTRIBUTION.COFINANCING_AMOUNT',

  COMPONENT = 'FI.CNVG.FP.PROCUREMENT.COMPONENT',
  OUTPUT = 'FI.CNVG.FP.PROCUREMENT.OUTPUT',
  ASSIGNED_AMOUNT = 'FI.CNVG.FP.PROCUREMENT.%_ASSIGNED_AMOUNT',

  MILESTONE = 'FI.CNVG.FP.PROCUREMENT.PROCESS.MILESTONE',
  ESTIMATED_DATE = 'FI.CNVG.FP.PROCUREMENT.PROCESS.ESTIMATED_DATE',
  RE_ESTIMATED_DATE = 'FI.CNVG.FP.PROCUREMENT.PROCESS.RE_ESTIMATED_DATE',
  ACTUAL_DATE = 'FI.CNVG.FP.PROCUREMENT.PROCESS.ACTUAL_DATE',

  SUSTAINABILITY_LABEL = 'FI.CNVG.FP.PROCUREMENT.SUSTAINABILITY.SUSTAINABILITY_LABEL',
  SUSTAINABILITY_DESCRIPTION_LABEL = 'FI.CNVG.FP.PROCUREMENT.SUSTAINABILITY.SUSTAINABILITY_DESCRIPTION_LABEL',

  LOTS = 'FI.CNVG.FP.PROCUREMENT.LOTS',
  SEPA = 'FI.CNVG.FP.PROCUREMENT.SEPA',
  BAFO = 'FI.CNVG.FP.PROCUREMENT.BAFO',
  GOODS_AND_SERVICES = 'FI.CNVG.FP.PROCUREMENT.GOODS_AND_SERVICES',
}
