export enum DocumentPackageCode {
  SPN = 25,
  EOI = 10,
  NOA_FIRMS = 21,
  NOA_GOODS = 3,
}

export enum DocumentPackageName {
  BIDDING_PACKAGES_BID_OPEN_FINANCIAL = 0,
  BIDDING_PACKAGES_BID_OPEN_RECORD = 1,
  BIDDING_PACKAGES_BID_OPEN_RECORD_TECHNICAL = 2,
  BIDDING_PACKAGES_CONTR_AWARD = 3,
  BIDDING_PACKAGES_DIRECT_CONTRACT = 4,
  BIDDING_PACKAGES_EVALUATION = 5,
  BIDDING_PACKAGES_EVALUATION_EX = 6,
  BIDDING_PACKAGES_EVALUATION_REPORT = 7,
  BIDDING_PACKAGES_EVALUATION_TECHNICAL = 8,
  BIDDING_PACKAGES_EVAR = 9,
  BIDDING_PACKAGES_EXPRESSION = 10,
  BIDDING_PACKAGES_FINAL_EVA_CONTRACT_NEGO_EX = 11,
  BIDDING_PACKAGES_FINAL_EVA_REPORT_NEGO_CONT = 12,
  BIDDING_PACKAGES_FINANCIAL_PROPOSALS = 13,
  BIDDING_PACKAGES_FINANCIAL_PROPOSALS_EX = 14,
  BIDDING_PACKAGES_INV_PRE_BIDDER = 15,
  BIDDING_PACKAGES_JUSTIFICATION = 16,
  BIDDING_PACKAGES_JUSTIFICATION_EX = 17,
  BIDDING_PACKAGES_JUSTIFICATION_FORCE = 18,
  BIDDING_PACKAGES_LOCAL_GENERAL = 19,
  BIDDING_PACKAGES_NAT_SYS_GENERAL = 20,
  BIDDING_PACKAGES_NOTIFICATION = 21,
  BIDDING_PACKAGES_PRE_EVAL_REPORT = 22,
  BIDDING_PACKAGES_PROP_OPEN_REC = 23,
  BIDDING_PACKAGES_PROP_OPEN_REC_EX = 24,
  BIDDING_PACKAGES_PROPOSED_BID = 25,
  BIDDING_PACKAGES_PROPOSED_NOTICE = 26,
  BIDDING_PACKAGES_REQUEST_PROPOSALS = 27,
  BIDDING_PACKAGES_REQUEST_PROPOSALS_EX = 28,
  BIDDING_PACKAGES_TECHNICAL_REPORT = 29,
  BIDDING_PACKAGES_TERM_REF_OPEN_INV = 30,
}

/**
 * The enum below is used to identified the notice type when publishing it
 */
export enum NoticeTypeEnum {
  AGA = 0,
  EOI,
  SPN,
  NOA,
}

export const DocumentPackageCodeToNoticeType: Record<
  DocumentPackageCode,
  NoticeTypeEnum
> = {
  [DocumentPackageCode.EOI]: NoticeTypeEnum.EOI,
  [DocumentPackageCode.SPN]: NoticeTypeEnum.SPN,
  [DocumentPackageCode.NOA_FIRMS]: NoticeTypeEnum.NOA,
  [DocumentPackageCode.NOA_GOODS]: NoticeTypeEnum.NOA,
};
