export enum ContractMenuOptionsEnum {
  DELETE = 'CONTRACT.OPTIONS.DELETE',
  AMENDMENT = 'CONTRACT.OPTIONS.AMENDMENT',
  TERMINATE = 'CONTRACT.OPTIONS.TERMINATE',
  EDIT = 'CONTRACT.OPTIONS.EDIT',
  COMPLETE = 'CONTRACT.OPTIONS.COMPLETE',
}

export enum ParticipantMenuOptionsEnum {
  SEE = 'PARTICIPANT.SEE',
  REMOVE = 'PARTICIPANT.REMOVE',
}

export enum ComentMenuOptionsEnum {
  REPLY = 'FORMS.COMMENT_MENU.REPLY',
  EDIT = 'FORMS.COMMENT_MENU.EDIT',
  EDIT_ANSWER = 'FORMS.COMMENT_MENU.EDIT_ANSWER',
  INCLUDE = 'FORMS.COMMENT_MENU.INCLUDE',
  DECLINE = 'FORMS.COMMENT_MENU.DECLINE',
  DELETE = 'FORMS.COMMENT_MENU.DELETE',
}
