export enum ProcurementMethod {
  PROCT_SRQOI = 4,
  PROCT_SRMQ = 5,
  PROCT_SSS_ADIR = 93,
  PROCT_DCS_ADIR = 92,
  PROCT_SSSIC_ADIR = 94,
}

export enum ProcurementMethodCode {
  PROCT_CBSSTE = 'PROCT_CBSSTE',
  PROCT_ICB = 'PROCT_ICB',
  PROCT_PFA = 'PROCT_PFA',
  PROCT_SRQOI = 'PROCT_SRQOI',
  PROCT_SRMQ = 'PROCT_SRMQ',
  PROCT_NCB = 'PROCT_NCB',
  PROCT_SSS_ADIR = 'PROCT_SSS_ADIR',
  PROCT_DCS_ADIR = 'PROCT_DCS_ADIR',
  PROCT_SSSIC_ADIR = 'PROCT_SSSIC_ADIR',
}
