import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { LoadProjectDataService } from '@fiduciary-interface/app/features/autogenerated-forms/services/load-project-data.service';
import { ActivatedRoute, NavigationEnd, Router } from '@angular/router';
import {
  NoticeType,
  OptionsFormModel,
  ProjectInfo,
} from '@fiduciary-interface/app/features/autogenerated-forms/models';
import {
  combineLatest,
  filter,
  map,
  mergeMap,
  Observable,
  startWith,
  Subject,
  Subscription,
  takeUntil,
  tap,
} from 'rxjs';
import {
  BiddingProcessDocumentPackage,
  BiddingProcessProcurementProcess,
  Currency,
  ErrorResponseValidations,
  Project,
} from '@core/models';
import {
  AccompanimentOptions,
  ElectronicOptions,
  LotsOptions,
  MatchingDirectionOptions,
} from '../../enums';
import {
  CategoryProcurement,
  PermissionEnum,
  ProcurementMethodCode,
} from '@core/enums';
import { FormType } from '@core/utils';
import {
  combineDateTime,
  minOneItemValidator,
  SpnSpdForm,
  SpnSpdFormAll,
  SpnSpdLotsForm,
  BidSecurityOptions,
} from '../../models/spn-spd.form';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { HttpErrorResponse } from '@angular/common/http';
import {
  BiddingProcessDocumentPackagesApiService,
  CommonApiService,
} from '@core/services/apis';
import { SpnService } from '../../services/bussiness/spn.service';
import { ProcurementNoticesService } from '../../services/api/procurement-notices.service';
import { MarginOfPreferenceWillBeGranted } from '../../enums/marginOfPreferenceWillBeGranted.enum';
import { TranslateService } from '@ngx-translate/core';
import {
  ConfirmCancelDialogData,
  ConfirmCancelDialogComponent,
} from '@fiduciary-interface/app/shared/components/confirm-cancel-dialog/confirm-cancel-dialog.component';
import { MatDialog } from '@angular/material/dialog';
import { NotificationGlobalService } from '@fiduciary-interface/app/shared';
import { BreadcrumbService } from 'xng-breadcrumb';
import { MatAutocompleteSelectedEvent } from '@angular/material/autocomplete';
import { MatSelectChange } from '@angular/material/select';
import { DocumentPackageCode } from '@core/enums/documentPackageCode.enum';
import { PermissionService } from '@core/services/app/permission/permission.service';

interface ProjectDataRequired {
  processName: string;
  processCode: string;
  procurementProcess: BiddingProcessProcurementProcess;
  selectedLanguage: string;
  selectedProject: Project;
  country: string;
}

@Component({
  selector: 'fi-register-spn-spd',
  templateUrl: './register-spn-spd.component.html',
  styleUrls: ['./register-spn-spd.component.scss'],
})
export class RegisterSpnSpdComponent implements OnInit, OnDestroy {
  private commonCurrenciesApiSvc = inject(CommonApiService);
  private procurementNoticesSvc = inject(ProcurementNoticesService);
  private projectDataSvc = inject(LoadProjectDataService);
  private translateService = inject(TranslateService);
  private spnSvc = inject(SpnService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);
  readonly permissionSvc = inject(PermissionService);
  private matDialogService = inject(MatDialog);
  private globalNotificationService = inject(NotificationGlobalService);
  private breadcrumbService = inject(BreadcrumbService);
  private processDocumentPackage = inject(
    BiddingProcessDocumentPackagesApiService
  );

  private destroy$ = new Subject<void>();
  private sub: Subscription = new Subscription();
  projectData$: Observable<ProjectDataRequired> =
    this.projectDataSvc.loadDatatoSpn();
  obsCurrency$ = this.commonCurrenciesApiSvc
    .getCurrencies()
    .pipe(map((data: Currency[]) => data));

  opcionesElectronic = Object.values(ElectronicOptions);
  opcionesElectronicEnum = ElectronicOptions;
  optionsSpnType = this.spnSvc.getSpnOptions();
  optionsLangs = this.spnSvc.getLangOptions();
  optionsUnits;

  procurementProcess: BiddingProcessProcurementProcess;
  spnForm: FormType<SpnSpdForm> = SpnSpdFormAll();
  currencies: Currency[];
  filteredCurrencies: Currency[];
  guaranteeFilteredCurrencies: Currency[];
  projectInfo: ProjectInfo;
  minDateOfSubmissionOfBids: Date;
  minBidOpeningDate: Date;
  allLoaded = false;
  registering = true;
  hasEditPermission: boolean;
  noLots: boolean = true;
  guarantee: boolean = true;
  preferedLanguage: string;
  visualizeDropdown: boolean;
  numberOfDecimalOptions: number;
  guaranteeAmountDecimalOptions: number;
  isSDP: boolean;
  minDate = new Date();
  data;
  packages: BiddingProcessDocumentPackage[];
  actualPackage: BiddingProcessDocumentPackage;
  isPublishVersion: boolean = false;
  projectNameEn: string;

  agaMinDate = new Date(338791785);

  bidSecurityOptions = BidSecurityOptions;
  procurementCategory = CategoryProcurement;
  noticeType = NoticeType;
  matchingDirectionOptions = MatchingDirectionOptions;

  constructor() {
    this.loadAllData();
  }

  ngOnInit(): void {
    this.hasEditPermission = this.permissionSvc.haveSomePermissions([
      PermissionEnum.ENTER_UPDATE_CONTRACT_PROCUREMENT_INFORMATION,
    ]);
  }

  pasteCleanupSettings = {
    convertMsLists: true,
    removeHtmlComments: true,
    // stripTags: ['span', 'h1'],
    // removeAttributes: ['lang'],
    removeMsClasses: true,
    removeMsStyles: true,
    removeInvalidHTML: true,
  };

  optionsLots: OptionsFormModel = {
    title: 'SPN.REGISTER_SPN.SECTION_4.PARAGRAPH_3',
    options: Object.values(LotsOptions),
    selectedOption: LotsOptions.NO_LOTS,
  };

  optionsGranted: OptionsFormModel = {
    title: '',
    options: Object.values(MarginOfPreferenceWillBeGranted),
    selectedOption: MarginOfPreferenceWillBeGranted.GRANTED,
  };

  accompanimentOptions: OptionsFormModel = {
    title: 'SPN.REGISTER_SPN.SECTION_12.ACCOMPANIMENT_OPTIONS.TITLE',
    options: Object.values(AccompanimentOptions),
    selectedOption: AccompanimentOptions.GUARANTEE,
  };

  matchingDirections: OptionsFormModel = {
    title: 'SPN.REGISTER_SPN.SECTION_12.OPENING_DIRECTION_OPTIONS.TITLE',
    options: Object.values(MatchingDirectionOptions),
    selectedOption: MatchingDirectionOptions.SAME,
  };

  previsualize() {
    if (this.spnForm.invalid) {
      this.spnForm.markAllAsTouched();
      this.showInvalidFormDialog();
      return;
    }

    if (!this.isEditRoute()) {
      this.createSpn();
    } else {
      this.updateSpn();
    }
  }

  getControlLength(control: string) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(
      this.spnForm.value[control],
      'text/html'
    );
    const length = doc.body.textContent.replace(/\s/g, '').trim().length;
    return length || 0;
  }

  patchValueForm(data: any) {
    this.spnForm.controls.agaCode.setValue(data.agaCode);
    this.spnForm.controls.agaPublicationDate.setValue(
      new Date(data.agaPublicationDate + 'T00:00:00')
    );
    this.spnForm.controls.agenciesWillBeCofinanced.setValue(
      data.agenciesWillBeCofinanced
    );
    this.spnForm.controls.withLots.setValue(
      data.withLots ? LotsOptions.LOTS : LotsOptions.NO_LOTS
    );
    if (data.lots.length >= 1) {
      this.spnForm.controls.lots.clear();
      data.lots = data.lots.sort((a, b) => a.number - b.number);
      data.lots.forEach((e) => {
        this.spnForm.controls.lots.push(
          new FormGroup({
            expectedTime: new FormControl(e.expectedTime),
            name: new FormControl(e.name),
            number: new FormControl(e.number),
            technicalSpecifications: new FormControl(e.technicalSpecifications),
            timeUnit: new FormControl(e.unitOfTime),
          })
        );
      });
    }
    this.spnForm.controls.projectName.setValue(data.projectName);
    this.spnForm.controls.worksToBeAcquired.setValue(data.worksToBeAcquired);
    this.spnForm.controls.timeQuantity.setValue(data.timeQuantity);
    this.spnForm.controls.timeUnit.setValue(data.unitOfTime);
    //TODO FILL LOTS
    this.spnForm.controls.exceptionalEligibilityRules.setValue(
      data.exceptionalEligibilityRules
    );
    this.spnForm.controls.qualificationRequirements.setValue(
      data.qualificationRequirements
    );
    this.spnForm.controls.languageOfBiddingDocuments.setValue(
      data.languageOfBiddingDocuments
    );
    this.spnForm.controls.nonRefundableAmountCurrency.setValue(
      data.nonRefundableCurrency
    );
    this.spnForm.controls.nonRefundableAmount.setValue(
      data.nonRefundableAmount
    );
    this.spnForm.controls.nonRefundableAmountPaymentMethod.setValue(
      data.nonRefundablePaymentMethod
    );
    this.spnForm.controls.howToSendBiddingDocument.setValue(
      data.howToSendBiddingDocument
    );
    this.spnForm.controls.linksRelatedWithTheDocument.setValue(
      data.linksRelatedWithTheDocument
    );
    this.spnForm.controls.dateOfSubmissionOfBids.setValue(
      data.dateOfSubmissionOfBids
    );
    this.spnForm.controls.electronicOffers.setValue(
      data.electronicOffers ? ElectronicOptions.YES : ElectronicOptions.NO
    );
    this.spnForm.controls.bidOpeningDate.setValue(data.bidOpeningDate);
    this.spnForm.controls.dateTimebidOpeningDate.setValue(
      data.bidOpeningDate.toISOString().match(/T(\d{2}:\d{2})/)[1]
    );
    this.spnForm.controls.typeOfAccompaniment.setValue(
      data.typeOfAccompaniment === 0
        ? AccompanimentOptions.GUARANTEE
        : AccompanimentOptions.MAINTENANCE
    );

    this.spnForm.controls.currency.setValue(
      data.bidMaintenanceGuaranteeCurrency
    );
    this.spnForm.controls.amountInCurrency.setValue(
      data.bidMaintenanceAmountInCurrency
    );
    this.spnForm.controls.percentageOfBidPrice.setValue(
      data.bidMaintenancePercentageOfBidPrice
    );

    this.spnForm.controls.bidSecurityOption.setValue(
      data.isAmount ? BidSecurityOptions.AMOUNT : BidSecurityOptions.PERCENTAGE
    );
    this.spnForm.controls.isSameOpeningAddress.setValue(
      data.isSameOpeningAddress
        ? MatchingDirectionOptions.SAME
        : MatchingDirectionOptions.DIFFERENT
    );
    this.spnForm.controls.bidOpeningAddress.setValue(data.bidOpeningAddress);
    this.spnForm.controls.bidSubmissionAddress.setValue(
      data.bidOpeningSubmission
    );
    this.spnForm.controls.dateTimeOfSubmissionOfBids.setValue(
      data.dateOfSubmissionOfBids.toISOString().match(/T(\d{2}:\d{2})/)[1]
    );
    this.spnForm.controls.recipient.controls.address.setValue(data.address);
    this.spnForm.controls.recipient.controls.executingAgency.setValue(
      data.executingAgency
    );
    this.spnForm.controls.recipient.controls.responsible.setValue(
      data.responsible
    );
    this.spnForm.controls.recipient.controls.phone.setValue(data.phone);
    this.spnForm.controls.recipient.controls.email.setValue(data.email);
    this.spnForm.controls.recipient.controls.website.setValue(data.website);
    this.spnForm.controls.responsiblePhone.setValue(data.responsiblePhone);
    this.spnForm.controls.responsibleEmail.setValue(data.responsibleEmail);
    this.spnForm.controls.responsibleName.setValue(data.responsibleName);
    this.spnForm.controls.responsibleAddress.setValue(data.responsibleAddress);
    this.spnForm.controls.recipient.controls.responsible.setValue(
      data.attention
    );

    if (this.isSDOGoods || this.isSDONCSVC) {
      this.spnForm.controls.mofMethod.patchValue(
        data.mofMethod === null ? false : data.mofMethod
      );
      this.spnForm.controls.negotiationMethod.patchValue(
        data.negotiationMethod === null ? false : data.negotiationMethod
      );
    }
  }

  calculateDate() {
    this.minDateOfSubmissionOfBids = new Date();
    this.minBidOpeningDate = new Date();
    const methodName = this.procurementProcess?.procurementMethod?.name;
    const daysToAdd =
      methodName === ProcurementMethodCode.PROCT_ICB ||
      methodName === ProcurementMethodCode.PROCT_CBSSTE
        ? 42
        : methodName === ProcurementMethodCode.PROCT_NCB
        ? 28
        : 0;
    if (daysToAdd) {
      this.minDateOfSubmissionOfBids.setDate(
        this.minDateOfSubmissionOfBids.getDate() + daysToAdd
      );
      this.minBidOpeningDate.setDate(
        this.minBidOpeningDate.getDate() + daysToAdd
      );
    }
  }

  getAgaData(projectBucketId: string, language: string) {
    return this.procurementNoticesSvc.getAgaInfo(projectBucketId).pipe(
      map((data) => {
        return {
          name: data.name[language],
          objective: data.objective[language],
          sector: data.sector[language],
        };
      })
    );
  }

  getUnitsOfTime(language: string) {
    return this.procurementNoticesSvc.unitsOfTime().pipe(
      map((data) => {
        return data.map((ut) => {
          return { id: ut.id, name: ut.names[language] };
        });
      })
    );
  }

  loadAllData() {
    let route$ = this.router.events.pipe(
      filter((event): event is NavigationEnd => event instanceof NavigationEnd),
      startWith({ url: this.router.url } as NavigationEnd)
    );
    this.sub.add(
      combineLatest([this.projectData$, this.obsCurrency$, route$])
        .pipe(
          tap(
            ([projectData]) =>
              (this.preferedLanguage = projectData.selectedLanguage)
          ),
          mergeMap(([projectData, currencies, route]) => {
            const baseObservables = [
              this.getAgaData(
                projectData.selectedProject.projectBucketId,
                this.preferedLanguage
              ),
              this.getUnitsOfTime(this.preferedLanguage),
            ];

            if (route.url.endsWith('/update')) {
              const noticeId = this.route.snapshot.params.noticeId;
              const processId = this.route.snapshot.params.processId;
              baseObservables.push(this.procurementNoticesSvc.getSpn(noticeId));
              baseObservables.push(
                this.processDocumentPackage.getBiddingProcessDocumentPackages(
                  processId,
                  false
                )
              );
            }
            return combineLatest(baseObservables).pipe(
              map((results) => {
                const [agaInfo, unitsOfTime, ...rest] = results;

                return {
                  agaInfo,
                  selectedProject: projectData,
                  procurementProcess: projectData.procurementProcess,
                  currencies,
                  unitsOfTime,
                  route,
                  ...(rest.length > 0 && { spnData: rest[0] }),
                  ...(rest.length > 0 && { packages: rest[1] }),
                };
              })
            );
          })
        )
        .subscribe((data) => {
          this.data = data;
          this.allLoaded = true;
          this.optionsUnits = data.unitsOfTime;
          if (data.packages) {
            this.packages = data.packages.biddingProcessDocumentPackage;
            this.actualPackage = this.packages.find(
              (p) => p.id === this.route.snapshot.params.packageId
            );
            this.isPublishVersion =
              this.actualPackage.code === DocumentPackageCode.SPN;
          }
          this.projectInfo = {
            institutionName: this.translateService.instant('COMMON.IDB'),
            executor: data.selectedProject.selectedProject.executor,
            country: data.selectedProject.country,
            projectName:
              data.selectedProject.selectedProject?.projectName[
                data.selectedProject.selectedLanguage
              ].trim(),
            operationNumber:
              data.selectedProject.selectedProject.operationNumber,
            contractNumber: data.selectedProject.selectedProject.contract,
            proposalTitle: data.selectedProject.processName,
            proposalNumber: data.selectedProject.processCode,
            economicSector: data.agaInfo.sector,
          };
          this.procurementProcess = data.procurementProcess;
          if (data.route.url.endsWith('/sdp')) {
            this.isSDP = true;
          } else {
            if (data.route.url.endsWith('/sdo')) {
              this.isSDP = false;
            } else {
              if (data.spnData) {
                this.isSDP = data.spnData.spnType === 'SDP';
              }
            }
          }
          this.spnSvc.isSDPNotice = this.isSDP;
          this.setBreadcrumb();
          this.initializeForm();

          if (!this.projectInfo.projectName) {
            this.spnForm.controls.projectName.setValue(
              data.selectedProject.selectedProject.nameEn
            );
          }
          if (data.spnData) {
            this.patchValueForm(data.spnData);
          }
          this.projectNameEn =
            data.selectedProject.selectedProject?.projectName['en'];
          this.prefillProjectName(
            this.projectInfo.projectName || this.projectNameEn
          );
          if (!this.isEditRoute()) {
            this.spnForm.controls.recipient.controls.executingAgency.setValue(
              this.projectInfo.executor
            );
          }
          this.currencies = [null, ...data.currencies];
          this.filteredCurrencies = [...this.currencies];
          this.guaranteeFilteredCurrencies = [...this.currencies];
          this.procurementProcess = data.procurementProcess;
          if (
            this.procurementProcess.category.name ===
            CategoryProcurement.PROCT_WORKS
          ) {
            this.visualizeDropdown = true;
          }

          // If its SDO Goods we dont have time units for works to acquire thus delete their validators
          if (this.isSDOGoods || this.isSDONCSVC) {
            const { timeQuantity, timeUnit } = this.spnForm.controls;
            timeQuantity.clearValidators();
            timeUnit.clearValidators();
            timeQuantity.updateValueAndValidity();
            timeUnit.updateValueAndValidity();
          }
          this.calculateDate();
          if (!this.isSDOGoods && !this.isSDONCSVC) {
            // If it's SDO Goods or SDO NCS listen for With Lots/Without Lots radio changes
            this.listenLotsChanges();
            this.lotsChangeUpdate(this.spnForm.controls.withLots.value);
          } else {
            // Otherwise we don't listen to With Lots/Without lots radio changes since these two forms don't have that radio group
            // We set the worksToBeAcquired control to required since its textbox its required and always shown in these cases
            this.spnForm.controls.worksToBeAcquired.setValidators(
              Validators.required
            );
          }
          this.prepareDataPreview();
          this.typeOfAccompanimentUpdate(
            this.spnForm.controls.typeOfAccompaniment.value
          );
          this.listenAccompanimentChanges();
          this.sameOpeningAddressUpdate(
            this.spnForm.controls.isSameOpeningAddress.value
          );
          this.listenSameOpeningAddressChangess();
          this.listenToBidSecurityOptionChanges(
            this.spnForm.controls.bidSecurityOption.value ||
              BidSecurityOptions.AMOUNT
          );
        })
    );
  }

  prefillProjectName(projectName: string) {
    if (this.isEditRoute()) return;
    const control = this.spnForm.controls.projectName;
    control.patchValue(projectName);
  }

  listenToBidSecurityOptionChanges(initialValue: BidSecurityOptions) {
    const { bidSecurityOption } = this.spnForm.controls;

    if (!bidSecurityOption.value) {
      bidSecurityOption.setValue(initialValue, { emitEvent: false });
    }

    this.spnForm.controls.bidSecurityOption.valueChanges
      .pipe(takeUntil(this.destroy$), startWith(initialValue))
      .subscribe((value: BidSecurityOptions) => {
        this.onBidSecurityOptionChange(value);
      });
  }

  lotsChangeUpdate(withLotsValue: string) {
    const { lots, worksToBeAcquired, timeQuantity, timeUnit } =
      this.spnForm.controls;
    [lots, worksToBeAcquired, timeQuantity, timeUnit].forEach((control) => {
      control.setValidators([]);
    });
    if (withLotsValue === LotsOptions.NO_LOTS) {
      [worksToBeAcquired, timeQuantity, timeUnit].forEach((control) => {
        control.setValidators(Validators.required);
      });
      lots.clear();
    } else {
      if (!this.isEditRoute()) {
        lots.push(SpnSpdLotsForm());
      } else {
        if (this.spnForm.controls.lots.length === 0) {
          lots.push(SpnSpdLotsForm());
        }
      }
      worksToBeAcquired.setValue(null);
      timeQuantity.setValue(null);
      timeUnit.setValue(null);
      lots.setValidators(minOneItemValidator);
    }

    [lots, worksToBeAcquired, timeQuantity, timeUnit].forEach((control) => {
      control.updateValueAndValidity({ emitEvent: false });
    });
  }

  listenLotsChanges() {
    this.spnForm.controls.withLots.valueChanges
      .pipe(
        takeUntil(this.destroy$),
        tap((value) => this.lotsChangeUpdate(value))
      )
      .subscribe();
  }

  typeOfAccompanimentUpdate(typeOfAccompaniment: string) {
    this.toggleBidGuaranteeControls(typeOfAccompaniment);
  }

  listenAccompanimentChanges() {
    this.spnForm.controls.typeOfAccompaniment.valueChanges
      .pipe(takeUntil(this.destroy$))
      .subscribe((data) => {
        this.typeOfAccompanimentUpdate(data);
      });
  }

  sameOpeningAddressUpdate(isSameOpeningAddressString: string) {
    const { isSameOpeningAddress, bidOpeningAddress, bidSubmissionAddress } =
      this.spnForm.controls;

    [isSameOpeningAddress, bidOpeningAddress, bidSubmissionAddress].forEach(
      (control) => control.setValidators([])
    );

    if (isSameOpeningAddressString === MatchingDirectionOptions.DIFFERENT) {
      bidSubmissionAddress.setValidators(Validators.required);
    }
    bidOpeningAddress.setValidators(Validators.required);

    [isSameOpeningAddress, bidOpeningAddress, bidSubmissionAddress].forEach(
      (control) => control.updateValueAndValidity({ emitEvent: false })
    );
  }

  listenSameOpeningAddressChangess() {
    this.spnForm.controls.isSameOpeningAddress.valueChanges
      .pipe(takeUntil(this.destroy$))
      .subscribe((data) => {
        this.sameOpeningAddressUpdate(data);
      });
  }

  prepareDataPreview() {
    this.spnForm.valueChanges.subscribe((value) => {
      this.noLots = value.withLots === LotsOptions.NO_LOTS;
      this.guarantee =
        value.typeOfAccompaniment === AccompanimentOptions.GUARANTEE;
    });
  }

  initializeForm() {
    this.spnForm = SpnSpdFormAll(this.isSDP);
    this.spnForm.controls.spnType.setValue(this.isSDP ? 'SDP' : 'SDO');
  }

  displayFn(option: string | null): string {
    return option ? option : '';
  }

  onInputCurrencyChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    const value = input.value;

    this.filteredCurrencies = this._filter(value);
  }

  onGuaranteeInputCurrencyChange(event: Event) {
    const input = event.target as HTMLInputElement;
    const value = input.value;

    this.guaranteeFilteredCurrencies = this._filter(value);
  }

  private _filter(value: string): (Currency | null)[] {
    if (!value || value === '') {
      return this.currencies;
    }

    const filterValue = value.toLowerCase();

    return this.currencies.filter((option) => {
      if (option === null) {
        return 'no selection'.includes(filterValue);
      }
      return option.currency.toLowerCase().includes(filterValue);
    });
  }

  onCurrencyBlur(): void {
    const currentValue =
      this.spnForm.controls.nonRefundableAmountCurrency?.value;

    if (currentValue) {
      const validCurrencies = this.currencies
        .filter((c) => c !== null)
        .map((c) => c!.currency);

      if (!validCurrencies.includes(currentValue)) {
        this.spnForm.controls.nonRefundableAmountCurrency?.setValue('');
        this.filteredCurrencies = [...this.currencies];
      }
    }
  }

  currencyChange() {
    const currency = this.spnForm.controls.nonRefundableAmountCurrency.value;
    if (currency) {
      this.numberOfDecimalOptions = this.currencies.find(
        (e) => e?.currency === currency
      ).numberOfDecimals;
    }
  }

  onGuaranteeCurrencyChange(event: MatAutocompleteSelectedEvent) {
    if (event.option.value) {
      this.guaranteeAmountDecimalOptions = this.currencies.find(
        (currency) => currency?.currency === event.option.value
      ).numberOfDecimals;
    }
  }

  mapRequest(formGroup: FormType<SpnSpdForm>) {
    const formValue = formGroup.value;
    let spnType = formValue.spnType;
    let agenciesWillBeCofinanced = formValue.agenciesWillBeCofinanced;
    let worksToBeAcquired = formValue.worksToBeAcquired;
    let withLots = formValue.withLots === LotsOptions.LOTS;
    let timeQuantity = formValue.timeQuantity;
    let timeUnit = formValue.timeUnit;
    let exceptionalEligibilityRules = formValue.exceptionalEligibilityRules;
    let qualificationRequirements = formValue.qualificationRequirements;
    let languageOfBiddingDocuments = formValue.languageOfBiddingDocuments;
    let nonRefundableAmount = formValue.nonRefundableAmount;
    let nonRefundableAmountCurrency = formValue.nonRefundableAmountCurrency;
    let isAmount = formValue.bidSecurityOption === BidSecurityOptions.AMOUNT;
    let nonRefundableAmountPaymentMethod =
      formValue.nonRefundableAmountPaymentMethod;
    let howToSendBiddingDocument = formValue.howToSendBiddingDocument;
    let linksRelatedWithTheDocument =
      formValue.linksRelatedWithTheDocument === '' ||
      formValue.linksRelatedWithTheDocument === null
        ? []
        : formValue.linksRelatedWithTheDocument;
    let dateOfSubmissionOfBids = combineDateTime(
      formValue.dateOfSubmissionOfBids,
      formValue.dateTimeOfSubmissionOfBids
    ).toISOString();
    let electronicOffers = formValue.electronicOffers === ElectronicOptions.YES;
    let bidOpeningDate = combineDateTime(
      formValue.bidOpeningDate,
      formValue.dateTimebidOpeningDate
    ).toISOString();

    let lots = formValue.lots;
    let typeOfAccompaniment =
      formValue.typeOfAccompaniment === AccompanimentOptions.GUARANTEE ? 0 : 1;
    let bidMaintenanceGuarantee = {
      isAmount: isAmount,
      currency: formValue.currency,
      amountInCurrency: formValue.amountInCurrency,
      percentageOfBidPrice: formValue.percentageOfBidPrice,
    };
    let isSameOpeningAddress =
      formValue.isSameOpeningAddress === MatchingDirectionOptions.SAME;
    let bidOpeningAddress = formValue.bidOpeningAddress;
    let bidSubmissionAddress = formValue.bidSubmissionAddress;
    let responsibleAddress = formValue.responsibleAddress;
    let responsibleName = formValue.responsibleName;
    let responsibleEmail = formValue.responsibleEmail;
    let responsiblePhone = formValue.responsiblePhone;
    let address = formValue.recipient.address;
    let executingAgency = formValue.recipient.executingAgency;
    let attention = formValue.recipient.responsible;
    let phone = formValue.recipient.phone;
    let email = formValue.recipient.email;
    let webSite = formValue.recipient.website;
    let projectName = formValue.projectName;
    let agaPublicationDate = formValue.agaPublicationDate
      .toISOString()
      .split('T')[0];
    let agaCode = formValue.agaCode;
    let conditionalInfo;
    let marginOfPreferenceWillBeGranted =
      formValue.marginOfPreferenceWillBeGranted ===
      MarginOfPreferenceWillBeGranted.GRANTED;
    let mofMethod = formValue.mofMethod === null ? false : formValue.mofMethod;
    let negotiationMethod =
      formValue.negotiationMethod === null
        ? false
        : formValue.negotiationMethod;
    if (this.isSDP) {
      conditionalInfo = {
        marginOfPreferenceWillBeGranted: false,
        mofMethod: false,
        negotiationMethod: false,
      };
    } else {
      conditionalInfo = {
        marginOfPreferenceWillBeGranted,
        mofMethod,
        negotiationMethod,
      };
    }
    return {
      procurementMethod: this.procurementProcess.procurementMethod.name,
      documentPackageId: this.route.snapshot.paramMap.get('packageId'),
      spnType,
      agaCode,
      agaPublicationDate,
      worksToBeAcquired,
      agenciesWillBeCofinanced,
      withLots,
      lots,
      timeQuantity,
      timeUnit,
      exceptionalEligibilityRules,
      qualificationRequirements,
      languageOfBiddingDocuments,
      nonRefundableAmount,
      nonRefundableAmountCurrency,
      nonRefundableAmountPaymentMethod,
      howToSendBiddingDocument,
      linksRelatedWithTheDocument,
      dateOfSubmissionOfBids,
      electronicOffers,
      bidOpeningDate,
      typeOfAccompaniment,
      bidMaintenanceGuarantee,
      isAmount,
      isSameOpeningAddress,
      bidOpeningAddress,
      bidSubmissionAddress,
      responsibleAddress,
      responsibleName,
      responsibleEmail,
      responsiblePhone,
      address,
      executingAgency,
      attention,
      phone,
      email,
      webSite,
      projectName,
      ...conditionalInfo,
    };
  }

  createSpn(): void {
    this.allLoaded = false;
    this.procurementNoticesSvc
      .createSpn(this.mapRequest(this.spnForm))
      .subscribe({
        next: (data) => {
          this.allLoaded = true;
          const message = this.translateService.instant(
            'UNDB.SPN.FORM.SUCCESFUL_REGISTRATION'
          );
          this.globalNotificationService.showSuccess(message);
          this.goToPreview(data);
        },
        error: (err: HttpErrorResponse) => {
          const e = err.error as ErrorResponseValidations;
          const errorDetails = e.errors?.[0]?.description || '';
          const errorMessage =
            e.detail + (errorDetails ? '\n' + errorDetails : '');
          this.globalNotificationService.showError(errorMessage);
          this.allLoaded = true;
        },
      });
  }

  updateSpn(): void {
    const noticeId = this.route.snapshot.params.noticeId;
    this.allLoaded = false;
    this.procurementNoticesSvc
      .updateSpn(this.mapRequest(this.spnForm), noticeId)
      .subscribe({
        next: (_data) => {
          this.allLoaded = true;
          const message = this.translateService.instant(
            'UNDB.SPN.FORM.SUCCESFUL_UPDATE'
          );
          this.globalNotificationService.showSuccess(message);
          this.goToPreview(noticeId);
        },
        error: (err: HttpErrorResponse) => {
          const e = err.error as ErrorResponseValidations;
          const errorDetails = e?.errors[0]?.description;
          this.globalNotificationService.showError(
            e.detail + '\n' + errorDetails
          );
          this.allLoaded = true;
        },
      });
  }

  goToPreview(noticeId: string): void {
    this.router.navigate(['../../', noticeId, 'preview'], {
      relativeTo: this.route,
    });
  }

  goBack() {
    this.router.navigate(['../../../../..'], { relativeTo: this.route });
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
    this.sub.unsubscribe();
  }

  onSpnTypeChange(type: MatSelectChange) {
    if (!this.isEditRoute()) {
      this.router.navigate(['../', type.value.toLowerCase()], {
        relativeTo: this.route,
      });
    } else {
      const dialogData: ConfirmCancelDialogData = {
        headerIcon: 'info',
        headerEnum: 'SPN.CHANGE_NOTICE_TYPE_MODAL.HEADER',
        bodyTextEnum: 'SPN.CHANGE_NOTICE_TYPE_MODAL.BODY',
        cancelButtonEnum: 'SPN.CHANGE_NOTICE_TYPE_MODAL.CANCEL',
        confirmButtonEnum: 'SPN.CHANGE_NOTICE_TYPE_MODAL.CONFIRM',
      };
      const dialog = this.matDialogService.open(ConfirmCancelDialogComponent, {
        data: dialogData,
      });

      dialog
        .afterClosed()
        .pipe(
          tap((res) => {
            if (res) {
              this.spnSvc.isSDPNotice = type.value === 'SDP';
              this.reloadOnChangeType(type);
            } else {
              const previousValue =
                this.spnForm.controls.spnType.getRawValue() === 'SDP'
                  ? 'SDO'
                  : 'SDP';
              this.spnForm.controls.spnType.setValue(previousValue, {
                emitEvent: false,
              });
              this.spnForm.controls.spnType.markAsPristine();
            }
          })
        )
        .subscribe();
    }
  }

  reloadOnChangeType(type) {
    this.allLoaded = false;
    this.isSDP = type.value.toLowerCase() === 'sdp';
    setTimeout(() => {
      this.allLoaded = true;
      this.initializeForm();
      this.listenAccompanimentChanges();
      this.listenSameOpeningAddressChangess();
      this.listenToBidSecurityOptionChanges(BidSecurityOptions.AMOUNT);
      this.spnForm.controls.typeOfAccompaniment.setValue(
        AccompanimentOptions.GUARANTEE
      );
      this.spnForm.controls.bidSecurityOption.setValue(
        BidSecurityOptions.AMOUNT
      );
      this.sameOpeningAddressUpdate(MatchingDirectionOptions.SAME);
      this.spnForm.controls.recipient.controls.executingAgency.setValue(
        this.projectInfo.executor
      );
      this.spnForm.controls.projectName.setValue(
        this.projectInfo.projectName || this.projectNameEn
      );
      this.noLots = true;
      this.spnForm.controls.worksToBeAcquired.setValidators([
        Validators.required,
      ]);
      this.spnForm.controls.timeUnit.setValidators([Validators.required]);
      this.spnForm.controls.timeQuantity.setValidators([Validators.required]);
      this.listenLotsChanges();
      this.prepareDataPreview();
    }, 1000);
  }

  convertUtcToLocalDate(utcDate: string): Date {
    return new Date(utcDate + 'Z');
  }

  isEditRoute(): boolean {
    return this.router.url.includes('/update');
  }

  onBidSecurityOptionChange(selectedBidSecurityOption: BidSecurityOptions) {
    const {
      currency,
      amountInCurrency,
      percentageOfBidPrice,
      typeOfAccompaniment,
    } = this.spnForm.controls;

    if (typeOfAccompaniment.value === AccompanimentOptions.MAINTENANCE) {
      currency.disable();
      amountInCurrency.disable();
      percentageOfBidPrice.disable();
      return;
    }

    if (selectedBidSecurityOption === this.bidSecurityOptions.AMOUNT) {
      currency.enable();
      amountInCurrency.enable();
      currency.setValidators(Validators.required);
      amountInCurrency.setValidators(Validators.required);
      percentageOfBidPrice.disable();
      percentageOfBidPrice.reset();

      return;
    }

    currency.disable();
    amountInCurrency.disable();
    currency.reset();
    amountInCurrency.reset();
    percentageOfBidPrice.enable();
    percentageOfBidPrice.setValidators([
      Validators.min(0),
      Validators.max(100),
      Validators.required,
    ]);

    currency.updateValueAndValidity();
    amountInCurrency.updateValueAndValidity();
    percentageOfBidPrice.updateValueAndValidity();
  }

  toggleBidGuaranteeControls(typeOfAccompaniment: string) {
    const {
      currency,
      amountInCurrency,
      percentageOfBidPrice,
      bidSecurityOption,
    } = this.spnForm.controls;

    if (typeOfAccompaniment === AccompanimentOptions.GUARANTEE) {
      bidSecurityOption.enable();

      if (bidSecurityOption.value === BidSecurityOptions.AMOUNT) {
        currency.enable();
        amountInCurrency.enable();
        percentageOfBidPrice.disable();
      } else {
        currency.disable();
        amountInCurrency.disable();
        percentageOfBidPrice.enable();
      }
    } else {
      currency.disable();
      amountInCurrency.disable();
      percentageOfBidPrice.disable();
      bidSecurityOption.disable();
    }

    currency.updateValueAndValidity();
    amountInCurrency.updateValueAndValidity();
    percentageOfBidPrice.updateValueAndValidity();
    bidSecurityOption.updateValueAndValidity();
  }

  showInvalidFormDialog() {
    const dialogData: ConfirmCancelDialogData = {
      headerEnum: 'UNDB.FORM.INCOMPLETE_FORM.DIALOG.HEADER',
      bodyTextEnum: 'UNDB.FORM.INCOMPLETE_FORM.DIALOG.BODY',
      confirmButtonEnum: 'UNDB.FORM.INCOMPLETE_FORM.DIALOG.CONFIRM_BTN',
    };

    this.matDialogService.open(ConfirmCancelDialogComponent, {
      data: dialogData,
    });
  }

  onExit() {
    if (!this.spnForm.dirty) {
      this.goBack();
      return;
    }
    const dialogData: ConfirmCancelDialogData = {
      headerIcon: 'info',
      headerEnum: 'UNDB.FORM.EXIT_DIALOG.HEADER',
      bodyTextEnum: 'UNDB.FORM.EXIT_DIALOG.BODY',
      cancelButtonEnum: 'ANT_TRANSACTION.CANCEL',
      confirmButtonEnum: 'UNDB.FORM.EXIT_DIALOG.CONFIRM_BTN',
    };

    if (this.isEditRoute()) {
      dialogData.bodyTextEnum = 'UNDB.FORM.EXIT_DIALOG.EDIT_EOI.BODY';
      dialogData.headerEnum = 'UNDB.FORM.EXIT_DIALOG.EDIT_EOI.HEADER';
    }

    const dialog = this.matDialogService.open(ConfirmCancelDialogComponent, {
      data: dialogData,
    });

    dialog
      .afterClosed()
      .pipe(
        tap((res) => {
          if (res) {
            this.goBack();
          }
        })
      )
      .subscribe();
  }

  setBreadcrumb() {
    if (this.isSDP) {
      this.breadcrumbService.set('@update-spn', 'SPN.TITLE');
      this.breadcrumbService.set('@register-spd', 'SPN.TITLE');
    } else {
      this.breadcrumbService.set(
        '@update-spn',
        'SPN.REGISTER_SPN.MODAL.OPTION.SDO.TITLE'
      );
      this.breadcrumbService.set(
        '@register-sdo',
        'SPN.REGISTER_SPN.MODAL.OPTION.SDO.TITLE'
      );
    }
  }

  get isSDOGoods(): boolean {
    return (
      !this.isSDP &&
      this.procurementProcess?.category.name ===
        this.procurementCategory.PROCT_GOODS
    );
  }

  get isSDONCSVC(): boolean {
    return (
      !this.isSDP &&
      this.procurementProcess?.category.name ===
        this.procurementCategory.PROCT_NCSVC
    );
  }
}
