export enum AccompanimentOptions {
  GUARANTEE = 'SPN.REGISTER_SPN.SECTION_12.ACCOMPANIMENT_OPTIONS.OPTION.GUARANTEE',
  MAINTENANCE = 'SPN.REGISTER_SPN.SECTION_12.ACCOMPANIMENT_OPTIONS.OPTION.MAINTENANCE',
}
