export enum LanguageOptions {
  ENGLISH = 'SPN.REGISTER_SPN.SECTION_8.SELECT.OPTION.ENGLISH',
  SPANISH = 'SPN.REGISTER_SPN.SECTION_8.SELECT.OPTION.SPANISH',
  FRENCH = 'SPN.REGISTER_SPN.SECTION_8.SELECT.OPTION.FRENCH',
  PORTUGUESE = 'SPN.REGISTER_SPN.SECTION_8.SELECT.OPTION.PORTUGUESE',
}
