export enum MatchingDirectionOptions {
  SAME = 'SPN.REGISTER_SPN.SECTION_12.OPENING_DIRECTION_OPTIONS.OPTION.SAME',
  DIFFERENT = 'SPN.REGISTER_SPN.SECTION_12.OPENING_DIRECTION_OPTIONS.OPTION.DIFFERENT',
}
