import { DocumentGroupMandatoryPublicationEnum } from '@core/enums';
import { ElementState, FiduciaryProcessDocument } from '.';
import { ParticipantAwarded } from './participant-awarded.model';
import { Enumerator, ParticipantPackages } from './responses';

export interface BiddingProcessDocumentPackage {
  id: string;
  status: number;
  code: number;
  totalMandatoryDocuments: number;
  totalUploadedDocuments: number;
  totalComments: number;
  order: number;
  requireNonObjection: boolean;
  actualDate: Date;
  isOptional?: boolean;
  biddingProcessDocumentGroups?: BiddingProcessDocumentGroup[];
  documentsToUpload: FiduciaryProcessDocument[];
  groupsState?: ElementState;
  documentsState?: ElementState;
  actualDateState?: ElementState;
  isReadOnly?: boolean;
  uploadedDocAfterCompletionExist?: boolean;
  bidValidityExtensionDate: Date;
}

export interface BiddingProcessDocumentGroup {
  id: string;

  /**
   * @fromEnum DocumentGroupCode
   */
  documentGroupCode: number;
  documentGroupConfiguration: BiddingProcessDocumentGroupConfiguration;
  fiduciaryProcessDocuments?: FiduciaryProcessDocument[];
  documentsState?: ElementState;
  options?: Enumerator[];
  participantsOptions?: ParticipantAwarded[];
  awardeds?: ParticipantPackages[];
  TypeResultMandatory?: boolean;
}

export interface BiddingProcessDocumentGroupConfiguration {
  id: string;

  /**
   * @fromEnum DocumentGroupVisibility
   */
  visibility: number;

  /**
   * @fromEnum DocumentGroupResult
   */
  isMandatory: boolean;
  isResult: boolean;
  isAmendment: boolean;
  isClarification: boolean;
  isDisclosed: boolean;
  result: number;
  disclosureRequiredAmount: boolean;
  isUniqueDocument: boolean;
  isAutogenerated: boolean;
  systemUpload: boolean;
  isMandatoryPublication: DocumentGroupMandatoryPublicationEnum;
}
