import { forwardRef, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { GpnRoutingModule } from './gpn-routing.module';
import { GpnComponent } from './views/gpn/gpn.component';
import {
  FormsModule,
  NG_VALUE_ACCESSOR,
  ReactiveFormsModule,
} from '@angular/forms';
import { StoreModule } from '@ngrx/store';
import { generalProcurementDocumentsReducer } from '@core/store';
import {
  DocumentsModule,
  LoaderModule,
  PipeModule,
} from '@fiduciary-interface/app/shared';
import { TranslateModule } from '@ngx-translate/core';
import { GpnDateModalComponent } from './components/gpn-date-modal/gpn-date-modal.component';
import { DateInputsModule } from '@progress/kendo-angular-dateinputs';
import { NumericTextBoxModule } from '@progress/kendo-angular-inputs';
import { LabelModule } from '@progress/kendo-angular-label';
import { projectSidebarVisibilityReducer } from '@core/store/visibility-project-sidebar/reducers/visibility-project-sidebar.reducer';
import { AutogeneratedFormsModule } from '../autogenerated-forms/autogenerated-forms.module';
import { OptionalParagraphComponent } from '../autogenerated-forms/components/optional-paragraph/optional-paragraph.component';

@NgModule({
  declarations: [GpnComponent, GpnDateModalComponent],
  imports: [
    CommonModule,
    GpnRoutingModule,
    FormsModule,
    LoaderModule,
    ReactiveFormsModule,
    DocumentsModule,
    PipeModule,
    TranslateModule,
    LabelModule,
    DateInputsModule,
    NumericTextBoxModule,
    StoreModule.forFeature(
      'generalProcurementDocuments',
      generalProcurementDocumentsReducer
    ),
    StoreModule.forFeature('projectSidebar', projectSidebarVisibilityReducer),
    AutogeneratedFormsModule,
    OptionalParagraphComponent,
  ],
  exports: [GpnComponent, GpnDateModalComponent],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => GpnComponent),
      multi: true,
    },
  ],
})
export class GpnModule {}
