import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { EoiRoutingModule } from './eoi-routing.module';
import { EoiComponent } from './views/eoi/eoi.component';
import { RegisterEoiComponent } from './views/register-eoi/register-eoi.component';
import { AutogeneratedFormsModule } from '../autogenerated-forms/autogenerated-forms.module';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatMomentDateModule } from '@angular/material-moment-adapter';
import { MatRadioModule } from '@angular/material/radio';
import { ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatButtonModule } from '@angular/material/button';
import { DirectivesModule, PipeModule } from '@fiduciary-interface/app/shared';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatIconModule } from '@angular/material/icon';
import { ConfirmCancelDialogModule } from '@fiduciary-interface/app/shared/components/confirm-cancel-dialog/confirm-cancel-dialog.module';
import { PreviewEoiComponent } from './views/preview-eoi/preview-eoi.component';
import { NotificationModule } from '@fiduciary-interface/app/shared';
import { EditorModule } from '@progress/kendo-angular-editor';

@NgModule({
  declarations: [EoiComponent, RegisterEoiComponent, PreviewEoiComponent],
  imports: [
    CommonModule,
    EoiRoutingModule,
    AutogeneratedFormsModule,
    MatFormFieldModule,
    MatInputModule,
    MatDatepickerModule,
    MatMomentDateModule,
    MatRadioModule,
    ReactiveFormsModule,
    TranslateModule,
    MatTooltipModule,
    MatButtonModule,
    DirectivesModule,
    MatProgressSpinnerModule,
    MatIconModule,
    ConfirmCancelDialogModule,
    NotificationModule,
    PipeModule,
    EditorModule,
  ],
})
export class EoiModule {}
