const errorPrefix = 'PROCUREMENT.VALIDATION_ERRORS.';

export const errorDefinitions = {
  'name-required': `${errorPrefix}NAME_REQUIRED`,
  'description-required': `${errorPrefix}DESCRIPTION`,
  'category-required': `${errorPrefix}CATEGORY`,
  'procurementMethod-required': `${errorPrefix}PROCUREMENT_METHOD`,
  'supervisionType-required': `${errorPrefix}SUPERVISION_METHOD`,
  'justification-required': `${errorPrefix}JUSTIFICATION`,
  'component-required': `${errorPrefix}COMPONENT`,
  'lots-required': `${errorPrefix}LOTS`,
  'bafo-required': `${errorPrefix}BAFO`,
  'bidAmount-required': `${errorPrefix}BID_AMOUNT`,
  'localCounterpartAmount-required': `${errorPrefix}LOCAL_COUNTERPART`,
  'cofinancingAmount-required': `${errorPrefix}COFINANCING_AMOUNT`,
  'x-id-required': `${errorPrefix}OUTPUT_#`,
  'x-percentage-required': `${errorPrefix}PERCENTAGE_ASIGNED_#`,
  'milestoneCollection-notOrdered': `${errorPrefix}MILESTONES_NOT_ORDERED`,
  'x-initialEstimationDate-required': `${errorPrefix}MILESTONE_DATE_REQUIRED_#`,
  'x-text-required': `${errorPrefix}COMMENT_REQUIRED`,
  'outputsAsigned-unassignedAmount': `${errorPrefix}OUTPUTS_UNASSIGNED_AMOUNT`,
  'goodsReference-required': `${errorPrefix}GOODS_REFERENCE`,
  'justification-nationalBiddingThresholdMaxError': `${errorPrefix}EXCEED_AMOUNT`,
  'maxAmount-nationalBiddingThresholdMaxError': `${errorPrefix}EXCEED_AMOUNT`,
  'maxThresholdExceed-maximunExceed': `${errorPrefix}EXCEED_TOTAL_THRESHOLD_AMOUNT`,
  'x-dateLowerToday': `${errorPrefix}DATE_LOWER_TODAY`,
  'maxThresholdExceed-maximunExceedCQS': `${errorPrefix}EXCEED_TOTAL_THRESHOLD_AMOUNT_CQS`,
  'maxThresholdExceedDirectContract-maximunExceed': `${errorPrefix}EXCEED_TOTAL_THRESHOLD_AMOUNT_DIRECT_CONTRACT`,
  'totalAmountPercentage-percentUncomplete': `${errorPrefix}ERROR_PERCENTAGE`,
  'x-disordered': `${errorPrefix}DATE_DISORDED_#`,
  'bidAmount-minError': `${errorPrefix}BID_AMOUNT_MIN_ERROR`,
  'localCounterpartAmount-minError': `${errorPrefix}LOCAL_COUNTERPART_AMOUNT_MIN_ERROR`,
  'cofinancingAmount-minError': `${errorPrefix}COFINANCING_AMOUNT_MIN_ERROR`,
  'minTotalAmount-minRequired': `${errorPrefix}TOTAL_AMOUNT_MIN_ERROR`,
};
