import { TestBed } from '@angular/core/testing';
import { BussinessRulesFunctionEnum } from '@fiduciary-interface/app/features/forms/enums/bussiness-rules-form.enum';
import { GroupNameTextEnum } from '@core/enums/groupCode.enum';
import { FormStatusEnum } from '@fiduciary-interface/app/features/forms/enums/form-status.enum';
import { BussinessRulesFormService } from '@fiduciary-interface/app/features/forms/services/bussiness-rules/bussiness-rules.service';
import { DocumentsGenerateService } from './documents-generate.service';

describe('DocumentsGenerateService', () => {
  let service: DocumentsGenerateService;
  let brFormServiceSpy: { filterBussinessRules: jest.Mock };

  beforeEach(() => {
    brFormServiceSpy = { filterBussinessRules: jest.fn() };

    TestBed.configureTestingModule({
      providers: [
        DocumentsGenerateService,
        { provide: BussinessRulesFormService, useValue: brFormServiceSpy },
      ],
    });

    service = TestBed.inject(DocumentsGenerateService);
  });

  describe('createRequestData', () => {
    it('should create the form request data', () => {
      const form = GroupNameTextEnum.BIDDINDG_DOC_SPECIFIC;
      const groupCode = 45;
      service.groups = groups;
      const resultBr = BussinessRulesFunctionEnum.GENERATE;
      const expectedFormData = {
        biddingDocumentId: undefined,
        biddingProcessPlanId: undefined,
        biddingProcessProcurementProcessId: undefined,
        categoryName: undefined,
        documentPackageId: '5bfeaa89-c2af-41c7-6e48-08db42784a97',
        fiduciaryProcessDocumentId: undefined,
        formName: 'BIDDINDG_DOC_SPECIFIC',
        formStatus: undefined,
        nameFile: undefined,
        operationNumber: undefined,
      };

      const result = service.createRequestData(form, groupCode, resultBr);
      expect(result).toEqual(expectedFormData);
      expect(brFormServiceSpy.filterBussinessRules).toHaveBeenCalledWith(
        resultBr
      );
    });

    // Test other cases...
  });

  describe('checkCreateStatusForm', () => {
    it('should return the corresponding form status', () => {
      const resultBr = BussinessRulesFunctionEnum.GENERATE;
      const expectedFormStatus = FormStatusEnum.CREATE;
      brFormServiceSpy.filterBussinessRules.mockReturnValue(expectedFormStatus);

      const result = service.checkCreateStatusForm(resultBr);

      expect(result).toBe(expectedFormStatus);
      expect(brFormServiceSpy.filterBussinessRules).toHaveBeenCalledWith(
        resultBr
      );
    });
  });
});

const groups = [
  {
    id: '2dc03825-4eb0-424b-6e47-08db42784a97',
    groupCode: 48,
    fiduciaryProcessDocuments: [],
    isMandatory: true,
    documentGroupConfiguration: {
      id: '23d81cdf-42cd-4591-aea3-08db42784a97',
      visibility: 0,
      result: 3,
      isMandatory: true,
      isResult: false,
      isAmendment: false,
      isClarification: false,
      isDisclosed: false,
      disclosureRequiredAmount: false,
      isUniqueDocument: true,
      isAutogenerated: false,
      systemUpload: false,
      isMandatoryPublication: null,
    },
  },
  {
    id: 'ffece596-71e5-41bb-6e49-08db42784a97',
    groupCode: 2,
    fiduciaryProcessDocuments: [],
    isMandatory: false,
    documentGroupConfiguration: {
      id: '43abaf8d-5144-4e6b-aea5-08db42784a97',
      visibility: 0,
      result: 3,
      isMandatory: false,
      isResult: false,
      isAmendment: true,
      isClarification: false,
      isDisclosed: false,
      disclosureRequiredAmount: false,
      isUniqueDocument: false,
      isAutogenerated: false,
      systemUpload: false,
      isMandatoryPublication: null,
    },
  },
  {
    id: '3fbc61bd-0342-4f1c-6e4a-08db42784a97',
    groupCode: 10,
    fiduciaryProcessDocuments: [],
    isMandatory: false,
    documentGroupConfiguration: {
      id: '65299e42-9053-4280-aea6-08db42784a97',
      visibility: 0,
      result: 3,
      isMandatory: false,
      isResult: false,
      isAmendment: false,
      isClarification: true,
      isDisclosed: false,
      disclosureRequiredAmount: false,
      isUniqueDocument: false,
      isAutogenerated: false,
      systemUpload: false,
      isMandatoryPublication: null,
    },
  },
  {
    id: '5bfeaa89-c2af-41c7-6e48-08db42784a97',
    groupCode: 45,
    fiduciaryProcessDocuments: [],
    isMandatory: true,
    documentGroupConfiguration: {
      id: '9013f475-2a9c-4ecc-aea4-08db42784a97',
      visibility: 0,
      result: 3,
      isMandatory: true,
      isResult: false,
      isAmendment: false,
      isClarification: false,
      isDisclosed: false,
      disclosureRequiredAmount: false,
      isUniqueDocument: true,
      isAutogenerated: true,
      systemUpload: false,
      isMandatoryPublication: null,
    },
  },
  {
    id: 'cc2a82bb-8615-4132-6e4c-08db42784a97',
    groupCode: 5,
    fiduciaryProcessDocuments: [],
    isMandatory: false,
    documentGroupConfiguration: {
      id: '17576a85-27bc-4dac-aea8-08db42784a97',
      visibility: 1,
      result: 3,
      isMandatory: false,
      isResult: false,
      isAmendment: false,
      isClarification: false,
      isDisclosed: false,
      disclosureRequiredAmount: false,
      isUniqueDocument: false,
      isAutogenerated: false,
      systemUpload: false,
      isMandatoryPublication: null,
    },
  },
  {
    id: '94da1b1d-8732-46ef-6e4b-08db42784a97',
    groupCode: 33,
    fiduciaryProcessDocuments: [],
    isMandatory: false,
    documentGroupConfiguration: {
      id: 'fedf6ea2-855f-4f5f-aea7-08db42784a97',
      visibility: 0,
      result: 3,
      isMandatory: false,
      isResult: false,
      isAmendment: false,
      isClarification: false,
      isDisclosed: false,
      disclosureRequiredAmount: false,
      isUniqueDocument: false,
      isAutogenerated: false,
      systemUpload: false,
      isMandatoryPublication: null,
    },
  },
];
