import { TestBed } from '@angular/core/testing';
import { BiddingProcessDocumentGroup } from '@core/models';
import { documentsInitialState } from '@core/store';
import { provideMockStore } from '@ngrx/store/testing';

import { BiddingProcessDocumentPackagesStoreService } from './bidding-process-document-packages-store.service';

describe('BiddingProcessDocumentPackagesStoreService', () => {
  let service: BiddingProcessDocumentPackagesStoreService;

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [provideMockStore({ initialState })],
    });
    service = TestBed.inject(BiddingProcessDocumentPackagesStoreService);
    (service as any).store.dispatch = jest.fn();
  });

  it('should get state by process id', () => {
    service.getDocumentPackagesByProcess('process-id-1').subscribe((state) => {
      expect(state).toEqual(
        documentsInitialState.biddingProcessDocumentPackagesByProcess[
          'process-id-1'
        ]
      );
    });
  });

  it('should call get document packages action', () => {
    service.getDocumentPackagesAction('process-id-5', false);

    expect((service as any).store.dispatch).toHaveBeenCalled();
  });

  it('should call get document groups action', () => {
    const biddingProcessDocumentGroups: BiddingProcessDocumentGroup[] = [
      {
        id: 'string',
        documentGroupCode: 0,
        documentGroupConfiguration: {
          id: 'string',
          visibility: 0,
          isMandatory: true,
          isResult: true,
          isAmendment: true,
          isClarification: true,
          isDisclosed: true,
          disclosureRequiredAmount: true,
          isUniqueDocument: true,
          isAutogenerated: true,
          result: 0,
          systemUpload: false,
          isMandatoryPublication: null,
        },
      },
    ];
    service.getDocumentGroupsAction(
      'process-id-5',
      'package-id-5',
      biddingProcessDocumentGroups
    );

    expect((service as any).store.dispatch).toHaveBeenCalled();
  });

  it('should call delete document action', () => {
    service.deleteDocument('process-id-5', 'package-id-5', null, null);

    expect((service as any).store.dispatch).toHaveBeenCalled();
  });

  it('should call add document packages action', () => {
    service.addDocumentPackagesAction('process-id-5', 'package-id-5', []);

    expect((service as any).store.dispatch).toHaveBeenCalled();
  });

  it('should call add document packages action with group', () => {
    service.addDocumentPackagesAction('process-id-5', 'package-id-5', [], 'id');

    expect((service as any).store.dispatch).toHaveBeenCalled();
  });

  it('should call change document package status action', () => {
    service.changeDocumentPackageStatusAction('process-id-5', 'package-id-5');

    expect((service as any).store.dispatch).toHaveBeenCalled();
  });
});

const initialState = {
  biddingProcessDocumentPackages: { ...documentsInitialState },
};
initialState.biddingProcessDocumentPackages.biddingProcessDocumentPackagesByProcess =
  {
    'process-id-1': {
      biddingProcessDocumentPackages: [
        {
          id: '123456',
          status: 0,
          code: 0,
          totalMandatoryDocuments: 0,
          totalUploadedDocuments: 0,
          totalComments: 0,
          order: 0,
          requireNonObjection: false,
          actualDate: new Date(),
          biddingProcessDocumentGroups: [],
          documentsToUpload: [],
          groupsState: { loading: false },
          documentsState: { loading: false },
          bidValidityExtensionDate: new Date(),
        },
      ],
      lastBidValidityExtensionDate: new Date('2023-03-04T04:00:00'),
      error: null,
      loaded: true,
      loading: false,
    },
  };
